force-app/main/default/objects/ZRH_MaestroGlosas__c/ZRH_MaestroGlosas__c.object-meta.xml
<CustomObject>
    <label>Maestro de glosas</label>
    <nameField>
        <displayFormat>G-{0000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de glosas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_Activo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Este campo indica si la glosa esta activa para su asignación al plan, sino esta activo no debe considerarse para las automatizaciones asociadas.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_ContenidoGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ContenidoGlosa__c</fullName>
    <description>Donde se almacena todo el detalle de la Glosa</description>
    <label>Contenido de Glosa</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_ContieneTabla__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ContieneTabla__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Contiene Tabla?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_DestinoTipoPDF__c.field-meta.xml
<CustomField>
    <fullName>ZRH_DestinoTipoPDF__c</fullName>
    <description>Permite diferenciar a que PDF va asociada la glosa</description>
    <label>Destino tipo de PDF</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D-001</fullName>
                <label>Póliza</label>
            </value>
            <value>
                <fullName>D-002</fullName>
                <label>Carta Oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_IDGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_IDGlosa__c</fullName>
    <label>ID Glosa</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_LocalizacionCondicionado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_LocalizacionCondicionado__c</fullName>
    <description>Ubicación de la glosa en el Condicionado Particular. Por ejemplo, si la &quot;Localización en Condicionado&quot; es igual a 3, quiere decir que esta debería corresponder a la tercera glosa ordenada secuencialmente desde la primera glosa al inicio de la página. Es importante notar que para la glosa del ejemplo anterior, no necesariamente existen dos glosas antes de ella. La razón de esto porque existen Glosas Condicionales que pueden activarse o no. Si una glosa Condicional hubiese tenido &quot;Localización en Condicionado! igual a dos, tendrá que aparecer en la posición 2 solo en caso de activarse, pero de no ser así , entonces la Glosa Estándar del ejemplo con posición igual a 3 habrá ocupado el espacio asignado de la 2. en resumen, este campo identifica el orden de aparición.</description>
    <label>Localizacion en Condicionado</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_LogicaCondiciones__c.field-meta.xml
<CustomField>
    <fullName>ZRH_LogicaCondiciones__c</fullName>
    <label>Lógica de Condiciones</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>AND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_Parametros__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Parametros__c</fullName>
    <description>Se especifican aquellos campos sobre los cuales hay que realizar validaciones o extraer datos para generar la glosa.</description>
    <label>Parámetros</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_Plan__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Plan__c</fullName>
    <description>Este campo define el plan para el cual aplicara la glosa, la glosa puede aplicar a uno o mas planes</description>
    <label>Plan</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>500</fullName>
            </value>
            <value>
                <fullName>501</fullName>
            </value>
            <value>
                <fullName>502</fullName>
            </value>
            <value>
                <fullName>600</fullName>
            </value>
            <value>
                <fullName>601</fullName>
            </value>
            <value>
                <fullName>602</fullName>
            </value>
            <value>
                <fullName>603</fullName>
            </value>
            <value>
                <fullName>604</fullName>
            </value>
            <value>
                <fullName>605</fullName>
            </value>
            <value>
                <fullName>606</fullName>
            </value>
            <value>
                <fullName>700</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_TipoDeGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoDeGlosa__c</fullName>
    <description>Puede ser una Glosa Estándar o una Glosa Condicional o Manual</description>
    <label>Tipo de Glosa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G-001</fullName>
                <label>Estándar</label>
            </value>
            <value>
                <fullName>G-002</fullName>
                <label>Condicional</label>
            </value>
            <value>
                <fullName>G-003</fullName>
                <label>Particular (Manual)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_Validaciones__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Validaciones__c</fullName>
    <description>En caso de tratarse de una Glosa Condicional, es necesario especificar las condiciones que debe validar SalesForce para determinar en que caso se incorpora dicha glosa.</description>
    <label>Validaciones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ZRH_MaestroGlosasSelector.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 27/09/2023
Description  : Query factory for master gloss using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda.             LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR            DATE              Description
1.0      ATO			27/09/2023		  initial version
********************************************************************************/
public class ZRH_MaestroGlosasSelector extends fflib_SObjectSelector{
    
    
    
    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        27/09/2023
    */
    public Schema.SObjectType getSObjectType(){
        return ZRH_MaestroGlosas__c.sObjectType;
    }
    
    
    /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            ZRH_MaestroGlosas__c.Id,
            ZRH_MaestroGlosas__c.OwnerId,
            ZRH_MaestroGlosas__c.IsDeleted,
            ZRH_MaestroGlosas__c.Name,
            ZRH_MaestroGlosas__c.CurrencyIsoCode,
            ZRH_MaestroGlosas__c.CreatedDate,
            ZRH_MaestroGlosas__c.CreatedById,
            ZRH_MaestroGlosas__c.LastModifiedDate,
            ZRH_MaestroGlosas__c.LastModifiedById,
            ZRH_MaestroGlosas__c.ZRH_LogicaCondiciones__c,
            ZRH_MaestroGlosas__c.SystemModstamp,
            ZRH_MaestroGlosas__c.ZRH_Activo__c,
            ZRH_MaestroGlosas__c.ZRH_ContenidoGlosa__c,
            ZRH_MaestroGlosas__c.ZRH_ContieneTabla__c,
            ZRH_MaestroGlosas__c.ZRH_DestinoTipoPDF__c,
            ZRH_MaestroGlosas__c.ZRH_IDGlosa__c,
            ZRH_MaestroGlosas__c.ZRH_LocalizacionCondicionado__c,
            ZRH_MaestroGlosas__c.ZRH_NombreArticulo__c,
            ZRH_MaestroGlosas__c.ZRH_NumeroArticulo__c,
            ZRH_MaestroGlosas__c.ZRH_Parametros__c,
            ZRH_MaestroGlosas__c.ZRH_Plan__c,
            ZRH_MaestroGlosas__c.ZRH_TipoDeGlosa__c,
            ZRH_MaestroGlosas__c.ZRH_Titulo__c,
            ZRH_MaestroGlosas__c.ZRH_Validaciones__c
        };
    }
    
    /**
    *  @Description: Perform a query with the default fields with the plan code of Glosas as a condition
    *  @Autor:       Luis Castañeda Donaire, Deloitte, lcastanedad@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<ZRH_MaestroGlosas__c> selectByPlanCode(String planCode){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('ZRH_Activo__c = true and ZRH_Plan__c INCLUDES (:planCode)');
        return (List<ZRH_MaestroGlosas__c>) Database.query( query.toSOQL() );
    }

}