force-app/main/default/objects/ContractGroupPlan/fields/vlocity_ins_fsc__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins_fsc__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracted Plans</relationshipLabel>
    <relationshipName>OrderProductStd</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_AtributosReqMedicosSeleccionado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosReqMedicosSeleccionado__c</fullName>
    <label>Atributos Requistos Medicos Seleccionado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_AtributosRequisitosAsegurabilidad__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosRequisitosAsegurabilidad__c</fullName>
    <description>Se almacena los atributos gestionados de Requisitos de Asegurabilidad.</description>
    <label>Atributos Requisitos de Asegurabilidad.</label>
    <length>98304</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>vlocity_ins_fsc__Product2Id__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_GrupoDeCobertura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoDeCobertura__c</fullName>
    <formula>TEXT(vlocity_ins_fsc__Product2Id__r.ZRH_GrupoDeCobertura__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grupo de Cobertura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Tarifa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Tarifa__c</fullName>
    <description>Campo para almacenar la tarifa</description>
    <label>Tarifa</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ZRH_GrupoDeCobertura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoDeCobertura__c</fullName>
    <label>Grupo de Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>HOSPITALIZACIONES</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>MATERNIDAD</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AMBULATORIO</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>DENTAL</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>OTRAS PRESTACIONES</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>VIDA</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>PRESTACIONES EN CONVENIO</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>GRUPO PSIQUIATRIA Y PSICOLOGIA</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>CONV.CLINICA DAVILA/HOSP.CLINICO U.CHILE</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>ONCOLOGIA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <externalId>true</externalId>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_GrupoDeCobertura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoDeCobertura__c</fullName>
    <formula>TEXT(Product2.ZRH_GrupoDeCobertura__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grupo de Cobertura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/ZRH_Glosas__c.object-meta.xml
<CustomObject>
    <label>Glosas</label>
    <nameField>
        <label>Nombre Glosa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Glosas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_DestinoTipoPDF__c.field-meta.xml
<CustomField>
    <fullName>ZRH_DestinoTipoPDF__c</fullName>
    <description>Permite diferenciar a que PDF va asociada la glosa</description>
    <label>Destino tipo de PDF</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D-001</fullName>
                <label>Póliza</label>
            </value>
            <value>
                <fullName>D-002</fullName>
                <label>Carta Oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_IDGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_IDGlosa__c</fullName>
    <description>Identificador de Glosa</description>
    <label>ID Glosa</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_ModificacionGlosasEspeciales__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ModificacionGlosasEspeciales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modificación de Glosas Especiales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_PlanDelContrato__c.field-meta.xml
<CustomField>
    <fullName>ZRH_PlanDelContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan del Contrato</label>
    <referenceTo>ContractGroupPlan</referenceTo>
    <relationshipLabel>Glosas</relationshipLabel>
    <relationshipName>Glosas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZRH_RutaIntegracion__mdt/ZRH_RutaIntegracion__mdt.object-meta.xml
<CustomObject>
    <label>ZRH Ruta Integracion</label>
    <pluralLabel>ZRH Rutas Integraciones</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZRH_RutaIntegracion__mdt/fields/ZRH_RutaURL__c.field-meta.xml
<CustomField>
    <fullName>ZRH_RutaURL__c</fullName>
    <label>Ruta URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_ServicioIntegracion__mdt/ZRH_ServicioIntegracion__mdt.object-meta.xml
<CustomObject>
    <label>ZRH Servicio Integracion</label>
    <pluralLabel>ZRH Servicio Integraciones</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZRH_ServicioIntegracion__mdt/fields/ZRH_URLBase__c.field-meta.xml
<CustomField>
    <fullName>ZRH_URLBase__c</fullName>
    <label>URL Base</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZRH_BatchSubmitPolicyPDFAS400_TEST.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 27/11/2023
Description  : Class test for class ZRH_BatchSubmitPolicyPDFAS400
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda              LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      LEC          27/11/2023        initial version
********************************************************************************/
@isTest
public class ZRH_BatchSubmitPolicyPDFAS400_TEST {

    /**
    *  @Description: Static variables
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        27/11/2023  
    */
    private static final String QUERY_CONDITION = 'ContractGroupParentPlanId = null';
    private static final String SR_ASV_VIDA_NAME = 'ZRH_JSON_VidaASV';
    private static final String SR_ASV_SALUD_NAME = 'ZRH_JSON_SaludASV';
    private static final String SR_ASV_COBERTURA_NAME = 'ZRH_JSON_CoberturaASV';
    private static final String SR_TARIFA_SALUD_NAME = 'ZRH_JSON_SaludTarifa';
    private static final String SR_TARIFA_SCHOLARSHIP_NAME = 'ZRH_JSON_EscolaridadTarifa';
    private static final String SR_TARIFA_VIDA_NAME = 'ZRH_JSON_VidaTarifa';
    private static final String SR_REQ_MED_NAME = 'ZRH_JSON_RequisitosMedicos';
    private static final String SR_VIDA_REQ_ASEG_NAME = 'ZRH_JSON_VidaRA';
    private static final String INTEGRATION_BASE = 'ZRH_SegurosColectivos';
    private static final String INTEGRATION_ROUTE = 'ZRH_EnvioPDFPoliza';
    private static final String SR_BODY_RESPONSE = 'ZRH_JSON_InputPDF';
    private static final String SR_FOLIO_NUMBER = '1245-0';
    private static final String CODE_POLICY_GLOSS = 'D-001';
    private static final List<Decimal> SR_GLOSS_ID = new List<Decimal> {83,143};
    private static final String METHOD_NAME_PDF = 'executeGeneratePDF';
    private static final String METHOD_NAME_PROPOSAL = 'executeSubmitProposal';
    private static final String VARIABLE_NAME = 'ContractHoldingId';
    private static final String OBJECT_CONTRACT= 'Contract';
    private static final String OBJECT_CONTRACT_GROUP_PLAN = 'ContractGroupPlan';
    private static final String OBJECT_API_NAME = 'objectApiName';
    private static final String RECORD_ID = 'recordId';
    
     @testSetup 
    static void setupMethod() {
        StaticResource vidaASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_VIDA_NAME);
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);
        StaticResource coberturaASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_COBERTURA_NAME);
        StaticResource saludTarifa = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_TARIFA_SALUD_NAME);
        StaticResource vidaTarifa = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_TARIFA_VIDA_NAME);
        StaticResource vidaRA = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_VIDA_REQ_ASEG_NAME);
        StaticResource vidaRM = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_REQ_MED_NAME);
        
        Account testAccount = ZRH_DataFactory.createAccount(true);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);
        Product2 testHealthProduct = ZRH_DataFactory.createHealthProduct(true);
        Product2 testLifeProduct = ZRH_DataFactory.createLifeProduct(true);
        Product2 testPersonalAccidentsProduct = ZRH_DataFactory.createPersonalAccidentsProduct(true);
        PricebookEntry testPricebookEntryHealth = ZRH_DataFactory.createPricebookEntry(true, testHealthProduct);
        PricebookEntry testPricebookEntryLife = ZRH_DataFactory.createPricebookEntry(true, testLifeProduct);
        PricebookEntry testPricebookEntryPersonalAccidents = ZRH_DataFactory.createPricebookEntry(true, testPersonalAccidentsProduct);
        Quote testQuoteOne = ZRH_DataFactory.createQuote(true, testOpportunity);
        
        QuoteLineItem testQuoteLineItemOne = ZRH_DataFactory.createQuoteLineItem(true, testQuoteOne, testLifeProduct, testPricebookEntryLife, vidaASV.Body.toString());
        QuoteLineItem testQuoteLineItemTwo = ZRH_DataFactory.createQuoteLineItem(true, testQuoteOne, testPersonalAccidentsProduct, testPricebookEntryPersonalAccidents,  vidaASV.Body.toString());
        
        ZRH_Glosas__c testGlosaHealthOne = ZRH_DataFactory.createRateGloss(true, testQuoteLineItemOne.Id);
        ZRH_Glosas__c testGlosaLifeOne = ZRH_DataFactory.createRateGloss(true, testQuoteLineItemOne.Id);
        ZRH_Glosas__c testGlosaLifeTwo = ZRH_DataFactory.createRequirementGloss(true, testQuoteLineItemOne.Id);
        ZRH_Glosas__c testGlosaLifeThree = ZRH_DataFactory.createMedicalRequirementGloss(true, testQuoteLineItemOne.Id);

        Contract testContract = ZRH_DataFactory.createContract(true, testQuoteOne, testAccount);
        ContractGroupPlan cgpOne = ZRH_DataFactory.createContractGroupPlan(true, testContract, testQuoteLineItemOne);
        ContractGroupPlan cgpTwo = ZRH_DataFactory.createContractGroupPlan(true, testContract, testQuoteLineItemTwo);
        
       
        
        cgpOne.ZRH_Tarifa__c = saludTarifa.Body.toString();
        cgpOne.ZRH_Folio__c = SR_FOLIO_NUMBER;
        cgpOne.ZRH_AtributosRequisitosAsegurabilidad__c = vidaRA.Body.toString();
        cgpOne.ZRH_AtributosReqMedicosSeleccionado__c = vidaRM.Body.toString();
        cgpOne.EffectiveStartDate = System.now();
        cgpOne.EffectiveEndDate = System.now().addYears(1);
        cgpOne.ContractGroupParentPlanId = null;
        cgpTwo.ContractGroupParentPlanId  = cgpone.Id;
        testGlosaHealthOne.ZRH_PlanDelContrato__c = cgpone.Id;
        testGlosaHealthOne.ZRH_DestinoTipoPDF__c = CODE_POLICY_GLOSS;
        testGlosaHealthOne.ZRH_ContieneTabla__c = true;
        Boolean modificacionGlosasEspeciales = false;
        testGlosaHealthOne.ZRH_ModificacionGlosasEspeciales__c = !modificacionGlosasEspeciales;
        testGlosaLifeOne.ZRH_PlanDelContrato__c = cgpone.Id;
        testGlosaLifeOne.ZRH_DestinoTipoPDF__c = CODE_POLICY_GLOSS;
        testGlosaLifeOne.ZRH_ContieneTabla__c = true;
        testGlosaLifeOne.ZRH_ModificacionGlosasEspeciales__c = !modificacionGlosasEspeciales;
        testGlosaLifeTwo.ZRH_PlanDelContrato__c = cgpone.Id;
        testGlosaLifeTwo.ZRH_DestinoTipoPDF__c = CODE_POLICY_GLOSS;
        testGlosaLifeTwo.ZRH_ContieneTabla__c = true;
        testGlosaLifeTwo.ZRH_ModificacionGlosasEspeciales__c = !modificacionGlosasEspeciales;
        testGlosaLifeThree.ZRH_PlanDelContrato__c = cgpone.Id;
        testGlosaLifeThree.ZRH_DestinoTipoPDF__c = CODE_POLICY_GLOSS;
        testGlosaLifeThree.ZRH_ContieneTabla__c = true;
        testGlosaLifeThree.ZRH_ModificacionGlosasEspeciales__c = !modificacionGlosasEspeciales;
        
        
        ZRH_Glosas__c testGlosaLifefuor = testGlosaLifeThree.clone(true);
        ZRH_Glosas__c testGlosaLifefive = testGlosaLifeThree.clone(true);
        testGlosaLifefuor.Id = null;
        testGlosaLifefuor.ZRH_IDGlosa__c = SR_GLOSS_ID[0];
        testGlosaLifefive.Id = null;
        testGlosaLifefive.ZRH_IDGlosa__c = SR_GLOSS_ID[1];
        
        update cgpone;
        update cgpTwo;
        update testGlosaHealthOne;
        update testGlosaLifeOne;
        update testGlosaLifeTwo;
        update testGlosaLifeThree;
        insert testGlosaLifefuor;
        insert testGlosaLifefive;
    }
    
    
    /**
    *  @Description: Test the for the class bathc ZRH_BatchSendPolicyPDFAS400
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        27/11/2023
    */
    @isTest 
    static void batchSubmitPolicyPDFAS400Test() {
        ZRH_RutaIntegracion__mdt path = ZRH_RutaIntegracion__mdt.getInstance(INTEGRATION_ROUTE);
        ZRH_ServicioIntegracion__mdt service = ZRH_ServicioIntegracion__mdt.getInstance(INTEGRATION_BASE);
        
        List<String> endPoint = new List<String>();
        endPoint.add(service.ZRH_URLBase__c + path.ZRH_RutaURL__c);
        List<String> resBody = new List<String>();
        resBody.add(SR_BODY_RESPONSE);
        ZRH_UtilityHttpRequestMock_TEST.getMultimock(endPoint, resBody, 200);
        
        Test.startTest();
        Id jobId = Database.executeBatch(new ZRH_BatchSubmitPolicyPDFAS400(QUERY_CONDITION), 1);
        System.assertEquals(jobId != null, true, 'It´s Worked!');
        Test.stopTest();
    }
    
     /**
    *  @Description: Test for the Method gloss
    *  @Autor:       Luis Castañeda, Deloitte
    *  @Date:        7/11/2023
    */
    @isTest
    static  void testGloss() {
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outputMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put(VARIABLE_NAME, UserInfo.getUserId());
        Test.startTest();
        ZRH_PolicyPDFController obj = new ZRH_PolicyPDFController();
        Boolean response = (Boolean) obj.invokeMethod(METHOD_NAME_PDF, inputMap, outputMap, options);
        inputMap.put(RECORD_ID, UserInfo.getUserId());
        inputMap.put(OBJECT_API_NAME, OBJECT_CONTRACT);
        response = (Boolean) obj.invokeMethod(METHOD_NAME_PROPOSAL, inputMap, outputMap, options);
        
        StaticResource escolTarifa = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_TARIFA_SCHOLARSHIP_NAME);
        ZRH_PolicyPDFController.mapRatesScholarShip(new ContractGroupPlan(ZRH_Tarifa__c = escolTarifa.Body.toString()));
        ZRH_PolicyPDFController.mapDeductibles(new ContractGroupPlan(ZRH_Tarifa__c = escolTarifa.Body.toString()));
        ZRH_PolicyPDFController.mapDeductiblesBySection(new ContractGroupPlan(ZRH_Tarifa__c = escolTarifa.Body.toString()));
        System.assertEquals(response, true, 'Working!');
        
        ContractGroupPlan cgpOne = [Select Id,ContractId, (Select Name,vlocity_ins_fsc__Product2Id__c, vlocity_ins_fsc__AttributeSelectedValues__c,ZRH_GrupoDeCobertura__c, ZRH_CodigoProducto__c from ChildContractGroupPlans) from ContractGroupPlan limit 1];
        Update new Product2 (Id = cgpOne.ChildContractGroupPlans[0].vlocity_ins_fsc__Product2Id__c, ProductCode = '12t');
        cgpOne = [Select Id,ContractId, (Select Name, vlocity_ins_fsc__Product2Id__c, vlocity_ins_fsc__AttributeSelectedValues__c,ZRH_GrupoDeCobertura__c, ZRH_CodigoProducto__c from ChildContractGroupPlans) from ContractGroupPlan  limit 1];
        ZRH_PolicyPDFController.mapDeductibles(cgpOne);
        ZRH_PolicyPDFController.mapDeductiblesBySection(cgpOne);
        Test.stopTest();   
    }

    
}