force-app/main/default/objects/ContractGroupPlan/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>vlocity_ins_fsc__Product2Id__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/ZRH_Glosas__c.object-meta.xml
<CustomObject>
    <label>Glosas</label>
    <nameField>
        <label>Nombre Glosa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Glosas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_Activo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo indica si la glosa esta activa para su asignación al plan, sino esta activo no debe considerarse para las automatizaciones asociadas.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_DestinoTipoPDF__c.field-meta.xml
<CustomField>
    <fullName>ZRH_DestinoTipoPDF__c</fullName>
    <description>Permite diferenciar a que PDF va asociada la glosa</description>
    <label>Destino tipo de PDF</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D-001</fullName>
                <label>Póliza</label>
            </value>
            <value>
                <fullName>D-002</fullName>
                <label>Carta Oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_IDGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_IDGlosa__c</fullName>
    <description>Identificador de Glosa</description>
    <label>ID Glosa</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_InsurancePolicy__c.field-meta.xml
<CustomField>
    <fullName>ZRH_InsurancePolicy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipName>RCondiciones_Particulares_Glosas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_LocalizacionCondicionado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_LocalizacionCondicionado__c</fullName>
    <description>Ubicación de la glosa en el Condicionado Particular. Por ejemplo, si la &quot;Localización en Condicionado&quot; es igual a 3, quiere decir que esta debería corresponder a la tercera glosa ordenada secuencialmente desde la primera glosa al inicio de la página. Es importante notar que para la glosa del ejemplo anterior, no necesariamente existen dos glosas antes de ella. La razón de esto porque existen Glosas Condicionales que pueden activarse o no. Si una glosa Condicional hubiese tenido &quot;Localización en Condicionado! igual a dos, tendrá que aparecer en la posición 2 solo en caso de activarse, pero de no ser así , entonces la Glosa Estándar del ejemplo con posición igual a 3 habrá ocupado el espacio asignado de la 2. en resumen, este campo identifica el orden de aparición.</description>
    <label>Localización en Condicionado</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_NombreArticulo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreArticulo__c</fullName>
    <description>Nombre del articulo relacionado a la glosa (Categoría glosa)</description>
    <label>Nombre Artículo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_NumeroArticulo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroArticulo__c</fullName>
    <description>N° de articulo que corresponde la glosa</description>
    <label>Número Artículo</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_Parametros__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Parametros__c</fullName>
    <description>Se especifican aquellos campos sobre los cuales hay que realizar validaciones o extraer datos para generar la glosa.</description>
    <label>Parámetros</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_Plan__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Plan__c</fullName>
    <description>Este campo define el plan para el cual aplicara la glosa, la glosa puede aplicar a uno o mas planes</description>
    <label>Plan</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>500</fullName>
            </value>
            <value>
                <fullName>501</fullName>
            </value>
            <value>
                <fullName>502</fullName>
            </value>
            <value>
                <fullName>600</fullName>
            </value>
            <value>
                <fullName>601</fullName>
            </value>
            <value>
                <fullName>602</fullName>
            </value>
            <value>
                <fullName>603</fullName>
            </value>
            <value>
                <fullName>604</fullName>
            </value>
            <value>
                <fullName>605</fullName>
            </value>
            <value>
                <fullName>606</fullName>
            </value>
            <value>
                <fullName>700</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_PlanDelContrato__c.field-meta.xml
<CustomField>
    <fullName>ZRH_PlanDelContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan del Contrato</label>
    <referenceTo>ContractGroupPlan</referenceTo>
    <relationshipLabel>Glosas</relationshipLabel>
    <relationshipName>Glosas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_Quote__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>RCondiciones_Particulares_Glosas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>ZRH_QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partida de presupuesto</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Glosas</relationshipLabel>
    <relationshipName>Glosas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_TipoDeGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoDeGlosa__c</fullName>
    <description>Puede ser una Glosa Estándar o una Glosa Condicional o Manual</description>
    <label>Tipo de Glosa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G-001</fullName>
                <label>Estándar</label>
            </value>
            <value>
                <fullName>G-002</fullName>
                <label>Condicional</label>
            </value>
            <value>
                <fullName>G-003</fullName>
                <label>Especial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_Titulo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Titulo__c</fullName>
    <label>Título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZRH_GlosasSelector.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 27/09/2023
Description  : Query factory for StaticResorces using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                      ACRONYM
Abdon Tejos O.              ATO
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO			27/09/2023		initial version
********************************************************************************/
public inherited sharing class ZRH_GlosasSelector extends fflib_SObjectSelector{

    /**
    *  @Description: Static variables
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    private static final Set<String> PVR_SET_TARGET;
    private static final String CODE_PARTICULAR_GLOSS;
    private static final String CODE_POLICY_GLOSS;

    /**
    *  @Description: Initialization of static variables
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    static {
        PVR_SET_TARGET = fillSetTarget();
        CODE_PARTICULAR_GLOSS = 'G-003';
        CODE_POLICY_GLOSS = 'D-001';
    }    

    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public Schema.SObjectType getSObjectType(){
        return ZRH_Glosas__c.sObjectType;
    }

    /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            ZRH_Glosas__c.Id,
            ZRH_Glosas__c.OwnerId,
            ZRH_Glosas__c.IsDeleted,
            ZRH_Glosas__c.Name,
            ZRH_Glosas__c.CurrencyIsoCode,
            ZRH_Glosas__c.CreatedDate,
            ZRH_Glosas__c.CreatedById,
            ZRH_Glosas__c.LastModifiedDate,
            ZRH_Glosas__c.LastModifiedById,
            ZRH_Glosas__c.SystemModstamp,
            ZRH_Glosas__c.ZRH_Activo__c,
            ZRH_Glosas__c.ZRH_ContenidoGlosa__c,
            ZRH_Glosas__c.ZRH_ContieneTabla__c,
            ZRH_Glosas__c.ZRH_DestinoTipoPDF__c,
            ZRH_Glosas__c.ZRH_IDGlosa__c,
            ZRH_Glosas__c.ZRH_InsurancePolicy__c,
            ZRH_Glosas__c.ZRH_LocalizacionCondicionado__c,
            ZRH_Glosas__c.ZRH_NombreArticulo__c,
            ZRH_Glosas__c.ZRH_NumeroArticulo__c,
            ZRH_Glosas__c.ZRH_Parametros__c,
            ZRH_Glosas__c.ZRH_Plan__c,
            ZRH_Glosas__c.ZRH_QuoteLineItem__c,
            ZRH_Glosas__c.ZRH_Quote__c,
            ZRH_Glosas__c.ZRH_TipoDeGlosa__c,
            ZRH_Glosas__c.ZRH_Titulo__c,
            ZRH_Glosas__c.ZRH_PlanDelContrato__c,
            ZRH_Glosas__c.ZRH_Validaciones__c
        };
    }

    /**
    *  @Description: Perform a query with the default fields with the Name of Glosas as a condition
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public ZRH_Glosas__c selectByStaticResourceNameWithLimit(String name){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Name = :name');
        query.setLimit( 1 );
        return (ZRH_Glosas__c) Database.query( query.toSOQL() );
    }

    /**
    *  @Description: Perform a query with the default fields with the ZRH_Quote__c of Glosas as a condition
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<ZRH_Glosas__c> selectBySetIds(Set<ID> idSet, Set<ID> idSetQLI) {
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        fflib_SObjectSelector qliSelector = new ZRH_QuoteLineItemsSelector();
        qliSelector.configureQueryFactoryFields(query, 'ZRH_QuoteLineItem__r');
        query.setCondition('ZRH_DestinoTipoPDF__c IN :PVR_SET_TARGET AND ZRH_QuoteLineItem__c IN :idSetQLI');
        //query.setCondition('ZRH_QuoteLineItem__c IN :idSetQLI');
        //query.setCondition('ZRH_DestinoTipoPDF__c IN :PVR_SET_TARGET AND (ZRH_Quote__c IN :idSet OR ZRH_QuoteLineItem__c IN :idSetQLI)');
        query.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<ZRH_Glosas__c>) Database.query( query.toSOQL() );
    }

    /**
    *  @Description: Perform a query with the default fields with the ZRH_QuoteLineItem__c of Glosas as a condition
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<ZRH_Glosas__c> selectByQLIId(Set<ID> idSet) {        
        fflib_QueryFactory query = newQueryFactory(false, false, true);        
        query.setCondition('ZRH_DestinoTipoPDF__c IN :PVR_SET_TARGET AND ZRH_QuoteLineItem__c IN :idSet');
        query.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<ZRH_Glosas__c>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Perform a query with the default fields with the ZRH_QuoteLineItem__c of Glosas as a condition
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<ZRH_Glosas__c> selectByQLIIdAndGlossType(String quoteLineItemId) {        
        fflib_QueryFactory query = newQueryFactory(false, false, true);        
        query.setCondition('ZRH_QuoteLineItem__c = :quoteLineItemId and ZRH_TipoDeGlosa__c != \''+ CODE_PARTICULAR_GLOSS +'\'');
        return (List<ZRH_Glosas__c>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Perform a query with the default fields with the ZRH_QuoteLineItem__c of Glosas as a condition
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<ZRH_Glosas__c> selectByContractGroupPlan(String recordId) {        
        fflib_QueryFactory query = newQueryFactory(false, false, true);
		query.selectField('ZRH_PlanDelContrato__r.ZRH_CodigoProducto__c');        
        query.setCondition('ZRH_PlanDelContrato__c = :recordId and ZRH_DestinoTipoPDF__c includes ( \''+ CODE_POLICY_GLOSS +'\')');
        return (List<ZRH_Glosas__c>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Perform a query with the default fields with the ZRH_QuoteLineItem__c
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<ZRH_Glosas__c> selectByQliIdOnly(String recordId) {        
        fflib_QueryFactory query = newQueryFactory(false, false, true);        
        query.setCondition('ZRH_QuoteLineItem__c = :recordId');
        query.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<ZRH_Glosas__c>) Database.query( query.toSOQL() );
    }

    /**
    *  @Description: Filling of the static target variable
    *  @Autor:       Abdon Tejos, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */    
    public static Set<String> fillSetTarget() {
        return new Set<String>{'D-002', 'D-001;D-002'};
    }
}