force-app/main/default/objects/Quote/fields/vlocity_ins__AgencyBrokerageId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__AgencyBrokerageId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency/Brokerage</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins__ProducerId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__ProducerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins__UnderwriterId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__UnderwriterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins_fsc__GroupCensusStdId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins_fsc__GroupCensusStdId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Census</label>
    <referenceTo>GroupCensus</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_AtributosAsistenciasSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosAsistenciasSeleccionados__c</fullName>
    <label>Atributos Asistencias Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_AtributosConveniosLineaSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosConveniosLineaSeleccionados__c</fullName>
    <label>Atributos Convenios Linea Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_AtributosConveniosSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosConveniosSeleccionados__c</fullName>
    <label>Atributos Convenios Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_AtributosSobreprimasSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosSobreprimasSeleccionados__c</fullName>
    <label>Atributos Sobreprimas Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CoberturaEnElExterior__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CoberturaEnElExterior__c</fullName>
    <label>Cobertura en el Exterior</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
                <default>true</default>
                <label>Si</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_ComisionCorredor__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ComisionCorredor__c</fullName>
    <description>Valor en porcentaje de la comisión del corredor</description>
    <label>Comisión Corredor</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_ConsideraTopePreexistencias__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ConsideraTopePreexistencias__c</fullName>
    <label>Considera Topes (UF)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CotizacionHolding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CotizacionHolding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Holding</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Cotizaciones Relacionadas</relationshipLabel>
    <relationshipName>ZRH_CotizacionHolding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CualesPreexistencias__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CualesPreexistencias__c</fullName>
    <label>Cúales Preexistencias</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Hipertensión Arterial</fullName>
            </value>
            <value>
                <fullName>Hipotiroidismo</fullName>
            </value>
            <value>
                <fullName>Hipertiroidismo</fullName>
            </value>
            <value>
                <fullName>Tiroiditis</fullName>
            </value>
            <value>
                <fullName>Bocio</fullName>
            </value>
            <value>
                <fullName>Resistencia a la Insulina</fullName>
            </value>
            <value>
                <fullName>Intolerancia a la Glucosa</fullName>
            </value>
            <value>
                <fullName>Depresión</fullName>
            </value>
            <value>
                <fullName>Dermatitis</fullName>
            </value>
            <value>
                <fullName>Asma</fullName>
            </value>
            <value>
                <fullName>Psoriasis</fullName>
            </value>
            <value>
                <fullName>Estrabismo</fullName>
            </value>
            <value>
                <fullName>Escoliosis</fullName>
            </value>
            <value>
                <fullName>Hernia Lumbar</fullName>
            </value>
            <value>
                <fullName>Hernia Nucleo Pulposo</fullName>
            </value>
            <value>
                <fullName>Vitiligo</fullName>
            </value>
            <value>
                <fullName>Acné</fullName>
            </value>
            <value>
                <fullName>Rosácea</fullName>
            </value>
            <value>
                <fullName>Reflujo Gastroesofágico</fullName>
            </value>
            <value>
                <fullName>Soplos</fullName>
            </value>
            <value>
                <fullName>Rinitis</fullName>
            </value>
            <value>
                <fullName>Varices Extremidades Inferiores</fullName>
            </value>
            <value>
                <fullName>Tendinitis</fullName>
            </value>
            <value>
                <fullName>Discopatía Lumbar</fullName>
            </value>
            <value>
                <fullName>Enfermedad Diverticular</fullName>
            </value>
            <value>
                <fullName>Varicoceles</fullName>
            </value>
            <value>
                <fullName>Osteopenia</fullName>
            </value>
            <value>
                <fullName>Osteoporosis</fullName>
            </value>
            <value>
                <fullName>Colitis Ulcerosa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CubrePreexistencias__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CubrePreexistencias__c</fullName>
    <label>Cubre Preexistencias</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CubreTodasPreexistencias__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CubreTodasPreexistencias__c</fullName>
    <label>Cubre Para Todas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Todas</fullName>
            </value>
            <value>
                <fullName>Solo las seleccionadas por la Compañía</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CuentasDEF__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CuentasDEF__c</fullName>
    <description>Campo para almacenar la información de las cuentas DEF.</description>
    <label>Cuentas DEF</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_FondoLibreDisposicion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_FondoLibreDisposicion__c</fullName>
    <label>Fondo Libre Disposición</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Si</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_Holding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Holding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo relación a cuenta Holding</description>
    <label>Holding</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Holding)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_IdJobCreacionPolizas__c.field-meta.xml
<CustomField>
    <fullName>ZRH_IdJobCreacionPolizas__c</fullName>
    <label>Id Job Creación Pólizas</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_Moneda__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Moneda__c</fullName>
    <description>Moneda de cotización</description>
    <label>Moneda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UF</fullName>
                <default>true</default>
                <label>UF</label>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_MontoAnualFondo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_MontoAnualFondo__c</fullName>
    <label>Monto Anual Fondo (UF)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_MontoTopePreexistencias__c.field-meta.xml
<CustomField>
    <fullName>ZRH_MontoTopePreexistencias__c</fullName>
    <label>Monto Tope (UF)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NivelAsistencia__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelAsistencia__c</fullName>
    <label>Nivel Asistencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo de Negocio</fullName>
            </value>
            <value>
                <fullName>Contratante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NivelConvenio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelConvenio__c</fullName>
    <label>Nivel de Convenios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo de Negocio</fullName>
            </value>
            <value>
                <fullName>Contratante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NivelConvenioLinea__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelConvenioLinea__c</fullName>
    <label>Nivel de Convenio en Linea</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo de Negocio</fullName>
            </value>
            <value>
                <fullName>Contratante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NivelDeCoberturaEnElExterior__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelDeCoberturaEnElExterior__c</fullName>
    <label>Nivel de Cobertura en el Exterior</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo de Negocio</fullName>
            </value>
            <value>
                <fullName>Contratante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NivelFondoLibreDisposicion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelFondoLibreDisposicion__c</fullName>
    <label>Nivel de Fondo Libre Disposición</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contratante</fullName>
            </value>
            <value>
                <fullName>Grupo de Negocio</fullName>
                <default>true</default>
                <label>Grupo de Negocio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NivelPreexistencia__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelPreexistencia__c</fullName>
    <label>Nivel de Preexistencias</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contratante</fullName>
            </value>
            <value>
                <fullName>Grupo de Negocio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NivelSobreprima__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelSobreprima__c</fullName>
    <label>Nivel Sobreprima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo de Negocio</fullName>
            </value>
            <value>
                <fullName>Contratante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ZRH_QuotesSelector.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 27/09/2023
Description  : Query factory for Quotes using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda.             LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO			27/09/2023		initial version
********************************************************************************/
public class ZRH_QuotesSelector extends fflib_SObjectSelector{

    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public Schema.SObjectType getSObjectType(){
        return Quote.sObjectType;
    }
    
    /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Quote.Id,
            Quote.OwnerId,
            Quote.IsDeleted,
            Quote.Name,
            Quote.AccountId,
            Quote.Pricebook2Id,
            Quote.vlocity_ins__AgencyBrokerageId__c,
            Quote.vlocity_ins__ProducerId__c,
            Quote.ZRH_Holding__c,
            Quote.ZRH_Moneda__c,
            Quote.ZRH_CotizacionHolding__c,
            Quote.ZRH_CuentasDEF__c,
            Quote.ZRH_IdJobCreacionPolizas__c,
            Quote.vlocity_ins_fsc__GroupCensusStdId__c,
            Quote.vlocity_ins__AgencyBrokerageId__c,
            Quote.vlocity_ins__ProducerId__c,
            Quote.vlocity_ins__UnderwriterId__c,
            Quote.ZRH_AtributosAsistenciasSeleccionados__c,
            Quote.ZRH_AtributosConveniosLineaSeleccionados__c,
            Quote.ZRH_AtributosConveniosSeleccionados__c,
            Quote.ZRH_AtributosSobreprimasSeleccionados__c,
            Quote.ZRH_CoberturaEnElExterior__c,
            Quote.ZRH_ComisionCorredor__c,
            Quote.ZRH_ConsideraTopePreexistencias__c,
            Quote.ZRH_CualesPreexistencias__c,
            Quote.ZRH_CubrePreexistencias__c,
            Quote.ZRH_CubreTodasPreexistencias__c,
            Quote.ZRH_FondoLibreDisposicion__c,
            Quote.ZRH_Holding__c,
            Quote.ZRH_Moneda__c,
            Quote.ZRH_MontoAnualFondo__c,
            Quote.ZRH_MontoTopePreexistencias__c,
            Quote.ZRH_NivelAsistencia__c,
            Quote.ZRH_NivelConvenio__c,
            Quote.ZRH_NivelConvenioLinea__c,
            Quote.ZRH_NivelDeCoberturaEnElExterior__c,
            Quote.ZRH_NivelFondoLibreDisposicion__c,
            Quote.ZRH_NivelPreexistencia__c,
            Quote.ZRH_NivelSobreprima__c,
            Quote.ZRH_NumeroDiasLibrePreexistencias__c,
            Quote.ZRH_PrimaTotalAnual_UF__c,
            Quote.ZRH_PrimaTotalAnualUF_Salud__c,
            Quote.ZRH_PrimaTotalAnualUF_Vida__c,
            Quote.ZRH_TipoTopePreexistencias__c,
            Quote.ZRH_TopeDeCobertura__c,
            Quote.ZRH_TopeTodasPreexistencias__c,
            Quote.ZRH_VigenciaInicio__c,
            Quote.ZRH_VigenciaTermino__c
        };
    }
    
    
    /**
    *  @Description: Perform a query by the Id and receiving the fields to which you want to query.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public Quote selectById(String recordId, List<String> fieldList) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField('Opportunity.OwnerId');
        for(String field: fieldList){
            query.selectField(field);
        }
        query.setCondition('Id = :recordId');
        return (Quote) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Make a query for a holding Quote
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<Quote> selectByQuoteHolding(String recordId) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(Quote.ZRH_AtributosCondicionadosParticulares__c);
        query.selectField('ZRH_CotizacionHolding__r.ZRH_RenovacionFlag__c'); 
        query.setCondition('ZRH_CotizacionHolding__c = :recordId');
        return (List<Quote>) Database.query( query.toSOQL() );
    }

    /**
    *  @Description: Get quotes from list of ids
    *  @Autor:       Mateo Long, Deloitte, mlongg@deloitte.com
    *  @Date:        30/10/2023
    */
    public Database.QueryLocator selectQuotesByIds(List<Id> quoteIds) { 
        return Database.getQueryLocator(
            newQueryFactory(false, false, true)
            .selectField(Quote.Id)            
            .selectField(Quote.ZRH_CotizacionHolding__c)            
            .selectField('Opportunity.AccountId')            
            .setCondition('Id IN :quoteIds')
            .toSOQL()
            );
    }

    /**
    *  @Description: Get quotes group
    *  @Autor:       Mateo Long, Deloitte, mlongg@deloitte.com
    *  @Date:        30/10/2023
    */
    public List<Quote> selectQuotesForGroup(Id quoteId) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(Quote.Id);           
        query.selectField(Quote.ZRH_CotizacionHolding__c);            
        query.selectField(Quote.vlocity_ins_fsc__GroupCensusStdId__c);
        query.selectField('Opportunity.AccountId');            
        query.setCondition('Id = :quoteId OR ZRH_CotizacionHolding__c = :quoteId');
        return (List<Quote>) Database.query( query.toSOQL() );
    }

        /**
    *  @Description: Get quotes group
    *  @Autor:       Mateo Long, Deloitte, mlongg@deloitte.com
    *  @Date:        19/12/2023
    */
    public List<Quote> selectQuotesFromGroupHolding(Id quoteId) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(Quote.Id);           
        query.selectField(Quote.ZRH_CotizacionHolding__c);            
        query.selectField(Quote.vlocity_ins_fsc__GroupCensusStdId__c);
        query.selectField('Opportunity.AccountId');            
        query.setCondition('ZRH_CotizacionHolding__c = :quoteId');
        return (List<Quote>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Get quote by set id
    *  @Autor:       Mateo Long, Deloitte, mlongg@deloitte.com
    *  @Date:        19/12/2023
    */
    public List<Quote> selectQuotesById(Set<Id> quoteIds) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(Quote.Id);           
        query.selectField(Quote.ZRH_CotizacionHolding__c);                                        
        query.selectField(Quote.Pricebook2Id);                    
        query.selectField(Quote.vlocity_ins__AgencyBrokerageId__c);                    
        query.selectField(Quote.vlocity_ins__ProducerId__c);
        query.selectField(Quote.vlocity_ins__UnderwriterId__c);
        query.selectField(Quote.ZRH_AtributosAsistenciasSeleccionados__c);
        query.selectField(Quote.ZRH_AtributosConveniosLineaSeleccionados__c);
        query.selectField(Quote.ZRH_AtributosConveniosSeleccionados__c);
        query.selectField(Quote.ZRH_AtributosSobreprimasSeleccionados__c);
        query.selectField(Quote.ZRH_CoberturaEnElExterior__c);
        query.selectField(Quote.ZRH_ComisionCorredor__c);
        query.selectField(Quote.ZRH_ConsideraTopePreexistencias__c);
        query.selectField(Quote.ZRH_CualesPreexistencias__c);
        query.selectField(Quote.ZRH_CubrePreexistencias__c);
        query.selectField(Quote.ZRH_CubreTodasPreexistencias__c);
        query.selectField(Quote.ZRH_FondoLibreDisposicion__c);
        query.selectField(Quote.ZRH_Holding__c);
        query.selectField(Quote.ZRH_Moneda__c);
        query.selectField(Quote.ZRH_MontoAnualFondo__c);
        query.selectField(Quote.ZRH_MontoTopePreexistencias__c);
        query.selectField(Quote.ZRH_NivelAsistencia__c);
        query.selectField(Quote.ZRH_NivelConvenio__c);
        query.selectField(Quote.ZRH_NivelConvenioLinea__c);
        query.selectField(Quote.ZRH_NivelDeCoberturaEnElExterior__c);
        query.selectField(Quote.ZRH_NivelFondoLibreDisposicion__c);
        query.selectField(Quote.ZRH_NivelPreexistencia__c);
        query.selectField(Quote.ZRH_NivelSobreprima__c);
        query.selectField(Quote.ZRH_NumeroDiasLibrePreexistencias__c);
        query.selectField(Quote.ZRH_PrimaTotalAnual_UF__c);
        query.selectField(Quote.ZRH_PrimaTotalAnualUF_Salud__c);
        query.selectField(Quote.ZRH_PrimaTotalAnualUF_Vida__c);
        query.selectField(Quote.ZRH_TipoTopePreexistencias__c);
        query.selectField(Quote.ZRH_TopeDeCobertura__c);
        query.selectField(Quote.ZRH_TopeTodasPreexistencias__c);
        query.selectField(Quote.Quote.vlocity_ins__ProducerId__c);                    
        query.selectField(Quote.Quote.ZRH_VigenciaInicio__c);                    
        query.selectField(Quote.Quote.ZRH_VigenciaTermino__c);                    
        query.selectField('Opportunity.AccountId');            
        query.setCondition('Id IN :quoteIds');
        return (List<Quote>) Database.query( query.toSOQL() );
    }


}