force-app/main/default/objects/Quote/fields/ZRH_CotizacionHolding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CotizacionHolding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Holding</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Cotizaciones Relacionadas</relationshipLabel>
    <relationshipName>ZRH_CotizacionHolding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__GroupClassId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__GroupClassId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Class</label>
    <referenceTo>vlocity_ins__GroupClass__c</referenceTo>
    <relationshipLabel>Quoted Plans</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/vlocity_ins__GroupClass__c/vlocity_ins__GroupClass__c.object-meta.xml
<CustomObject>
    <description>Group Class identifies a group of members that will all receive similar benefits, when different classes of members receive different benefits. Example classes may include Executives, Union and Office workers. Master-detail child object of an Employer/Group Account.</description>
    <label>Group Class</label>
    <nameField>
        <label>Group Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_ins__GroupClass__c/fields/vlocity_ins__GroupId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__GroupId__c</fullName>
    <label>Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Group Classes</relationshipLabel>
    <relationshipName>Group_Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ZRH_insQuoteController_TEST.cls
@isTest
public class ZRH_insQuoteController_TEST {
    
    private static final String SR_ASV_SALUD_NAME = 'ZRH_JSON_SaludASV';

    @isTest
    private static void getQuoteLineItemGroupClassesTest() {
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);
        Account testAccount = ZRH_DataFactory.createAccount(true);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);

        Product2 testLifeProduct = ZRH_DataFactory.createLifeProduct(true);
        PricebookEntry testPricebookEntryLife = ZRH_DataFactory.createPricebookEntry(true, testLifeProduct);
        
        Quote holdingQuote = ZRH_DataFactory.createQuote(true, testOpportunity);
        Quote testQuoteOne = ZRH_DataFactory.createQuote(false, testOpportunity);
        testQuoteOne.ZRH_CotizacionHolding__c = holdingQuote.Id;
        insert testQuoteOne;
        
        QuoteLineItem testQuoteLineItemOne = ZRH_DataFactory.createQuoteLineItem(true, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());
        
        vlocity_ins__GroupClass__c gc = new vlocity_ins__GroupClass__c();
        gc.Name = 'test';
        gc.vlocity_ins__IsActive__c = true;
        gc.vlocity_ins__GroupId__c = testAccount.Id;
        insert gc;

        vlocity_ins__QuoteLineItemGroupClass__c qliGC = new vlocity_ins__QuoteLineItemGroupClass__c();
        qliGC.vlocity_ins__GroupClassId__c = gc.Id;
        qliGC.vlocity_ins__QuoteLineItemId__c = testQuoteLineItemOne.Id;
        qliGC.vlocity_ins__QuoteId__c = testQuoteOne.Id;
        insert qliGC;

        Test.startTest();
        
        List<vlocity_ins__QuoteLineItemGroupClass__c> qliGCs = ZRH_insQuoteController.getQuoteLineItemGroupClasses(testQuoteOne.Id);
        Test.stopTest();

        System.assertEquals(1, qliGCs.size(), 'getQuoteLineItemGroupClassesTest failed');
    }

    @isTest
    private static void getRootQuoteLineItemsTest() {
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);
        Account testAccount = ZRH_DataFactory.createAccount(true);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);

        Product2 testLifeProduct = ZRH_DataFactory.createLifeProduct(true);
        PricebookEntry testPricebookEntryLife = ZRH_DataFactory.createPricebookEntry(true, testLifeProduct);
        
        Quote holdingQuote = ZRH_DataFactory.createQuote(true, testOpportunity);
        Quote testQuoteOne = ZRH_DataFactory.createQuote(false, testOpportunity);
        testQuoteOne.ZRH_CotizacionHolding__c = holdingQuote.Id;
        insert testQuoteOne;
        
        QuoteLineItem testQuoteLineItemOne = ZRH_DataFactory.createQuoteLineItem(true, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());

        Test.startTest();        
        List<Id> rootIds = ZRH_insQuoteController.getRootQuoteLineItems(testQuoteOne.Id);
        Test.stopTest();

        System.assertEquals(1, rootIds.size(), 'getRootQuoteLineItemsTest failed');
    }

    @isTest
    private static void getRootIdToCoverageCountQuoteLineItemsTest() {
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);
        Account testAccount = ZRH_DataFactory.createAccount(true);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);

        Product2 testLifeProduct = ZRH_DataFactory.createLifeProduct(true);
        PricebookEntry testPricebookEntryLife = ZRH_DataFactory.createPricebookEntry(true, testLifeProduct);
        
        Quote holdingQuote = ZRH_DataFactory.createQuote(true, testOpportunity);
        Quote testQuoteOne = ZRH_DataFactory.createQuote(false, testOpportunity);
        testQuoteOne.ZRH_CotizacionHolding__c = holdingQuote.Id;
        insert testQuoteOne;
        
        QuoteLineItem testQuoteLineItemOne = ZRH_DataFactory.createQuoteLineItem(true, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());

        Test.startTest();        
        Map<Id, Integer> rootIdToCovCt = ZRH_insQuoteController.getRootIdToCoverageCountQuoteLineItems(testQuoteOne.Id);
        Test.stopTest();

        System.assertEquals(true, rootIdToCovCt.containsKey(testQuoteLineItemOne.Id), 'getRootIdToCoverageCountQuoteLineItemsTest no key');
        System.assertEquals(0, rootIdToCovCt.get(testQuoteLineItemOne.Id), 'getRootIdToCoverageCountQuoteLineItemsTest count mismatch');
    }
}