force-app/main/default/objects/Contract/fields/ZRH_ContratoHolding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ContratoHolding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato Holding</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratos Relacionados</relationshipLabel>
    <relationshipName>ZRH_ContratoHolding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_NumeroDePoliza__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroDePoliza__c</fullName>
    <formula>IF(ZRH_Folio__c != &quot;&quot;, ZRH_Folio__c + &quot;-&quot; + TEXT(ZRH_Periodo__c), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número de Póliza</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_UsuarioAsignado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_UsuarioAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Asignado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Group_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZRH_PolicyAssingmentTableController.cls
public class ZRH_PolicyAssingmentTableController {
    
    @AuraEnabled
    public static List<Object> getContractGroupPlans(Id holdingContractId){
        try {
            List<ContractGroupPlan> contractGroupPlans = [SELECT Id, Name, Contract.Account.Name, ZRH_NumeroDePoliza__c, ZRH_UsuarioAsignado__r.Name FROM ContractGroupPlan WHERE ContractGroupParentPlanId = null AND Contract.ZRH_ContratoHolding__c = :holdingContractId LIMIT 400];
            
            List<Object> listCGP = new List<Object>();

            for (ContractGroupPlan cgp : contractGroupPlans) {
                Map<String,Object> field = new Map<String,Object>();
                field.put('Contratante', cgp.Contract.Account.Name);
                field.put('Plan', cgp.Name);
                field.put('NumeroPoliza', cgp.ZRH_NumeroDePoliza__c);
                field.put('UsuarioAsignado', cgp.ZRH_UsuarioAsignado__r.Name);
                field.put('Id', cgp.Id);
                listCGP.add(field);
            }

            return listCGP;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<ContractGroupPlan> assignUserToContractGroupPlans(Id userId, List<ContractGroupPlan> listCGP){
        try {
            System.debug('listCGP:' + listCGP);
            System.debug('userId:' + userId);
            for (ContractGroupPlan cgp : listCGP) {
                cgp.ZRH_UsuarioAsignado__c = userId;
            }
            update listCGP;

            return listCGP;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}