force-app/main/default/objects/Contract/fields/ZRH_AtributosAsistenciasSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosAsistenciasSeleccionados__c</fullName>
    <label>Atributos Asistencias Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ZRH_ContratoHolding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ContratoHolding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato Holding</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratos Relacionados</relationshipLabel>
    <relationshipName>ZRH_ContratoHolding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ZRH_CuentasDEF__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CuentasDEF__c</fullName>
    <label>Cuentas DEF</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ZRH_Holding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Holding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo relación a cuenta Holding</description>
    <label>Holding</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos (Holding)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_AtributosRequisitosAsegurabilidad__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosRequisitosAsegurabilidad__c</fullName>
    <description>Se almacena los atributos gestionados de Requisitos de Asegurabilidad.</description>
    <label>Atributos Requisitos de Asegurabilidad.</label>
    <length>98304</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_EndosoEnviado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_EndosoEnviado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endoso Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Periodo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Periodo__c</fullName>
    <label>Período</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Tarifa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Tarifa__c</fullName>
    <description>Campo para almacenar la tarifa</description>
    <label>Tarifa</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_AtributosAsistenciasSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosAsistenciasSeleccionados__c</fullName>
    <label>Atributos Asistencias Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CuentasDEF__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CuentasDEF__c</fullName>
    <description>Campo para almacenar la información de las cuentas DEF.</description>
    <label>Cuentas DEF</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_Holding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Holding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo relación a cuenta Holding</description>
    <label>Holding</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Holding)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__AttributeSelectedValues__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__AttributeSelectedValues__c</fullName>
    <label>Attribute Selected Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__ParentItemId2__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__ParentItemId2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Item Id</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items (Parent Item Id)</relationshipLabel>
    <relationshipName>ParentItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_AtributosBMI__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosBMI__c</fullName>
    <label>Atributos BMI</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <externalId>true</externalId>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_Periodo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Periodo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Período</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/ZRH_Glosas__c.object-meta.xml
<CustomObject>
    <label>Glosas</label>
    <nameField>
        <label>Nombre Glosa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Glosas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_Parametros__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Parametros__c</fullName>
    <description>Se especifican aquellos campos sobre los cuales hay que realizar validaciones o extraer datos para generar la glosa.</description>
    <label>Parámetros</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ZRH_Glosas__c/fields/ZRH_TipoDeGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoDeGlosa__c</fullName>
    <description>Puede ser una Glosa Estándar o una Glosa Condicional o Manual</description>
    <label>Tipo de Glosa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G-001</fullName>
                <label>Estándar</label>
            </value>
            <value>
                <fullName>G-002</fullName>
                <label>Condicional</label>
            </value>
            <value>
                <fullName>G-003</fullName>
                <label>Especial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/ZRH_MaestroGlosas__c.object-meta.xml
<CustomObject>
    <label>Maestro de glosas</label>
    <nameField>
        <displayFormat>G-{0000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de glosas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_LogicaCondiciones__c.field-meta.xml
<CustomField>
    <fullName>ZRH_LogicaCondiciones__c</fullName>
    <label>Lógica de Condiciones</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>AND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_Parametros__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Parametros__c</fullName>
    <description>Se especifican aquellos campos sobre los cuales hay que realizar validaciones o extraer datos para generar la glosa.</description>
    <label>Parámetros</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ZRH_MaestroGlosas__c/fields/ZRH_TipoDeGlosa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoDeGlosa__c</fullName>
    <description>Puede ser una Glosa Estándar o una Glosa Condicional o Manual</description>
    <label>Tipo de Glosa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G-001</fullName>
                <label>Estándar</label>
            </value>
            <value>
                <fullName>G-002</fullName>
                <label>Condicional</label>
            </value>
            <value>
                <fullName>G-003</fullName>
                <label>Particular (Manual)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/ZRH_SincronizacionEndoso__c.object-meta.xml
<CustomObject>
    <label>Sincronización de Endoso</label>
    <nameField>
        <displayFormat>SE-{00000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sincronización de Endosos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_CampoCondicion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CampoCondicion__c</fullName>
    <description>Cuando en el campo JSON se guarden una lista se debe agregar el campo que hace único en cada item.</description>
    <label>Campo Condición</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_CampoCondicionDos__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CampoCondicionDos__c</fullName>
    <label>Campo Condición Dos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <label>Folio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_NombreAtributo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreAtributo__c</fullName>
    <description>Guarda el nombre del atributo que se quiere actualizar</description>
    <label>Nombre de Atributo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_NombreCampo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreCampo__c</fullName>
    <description>Guarda el nombre del campo que se va a actualizar.</description>
    <label>Nombre del Campo Salesforce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_NombreObjeto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreObjeto__c</fullName>
    <description>Almacenará el nombre del objeto que se desea actualizar.</description>
    <label>Nombre del Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_TipoCampo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoCampo__c</fullName>
    <description>Guarda s</description>
    <label>Tipo de Campo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campo Salesforce</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_TipoEndoso__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoEndoso__c</fullName>
    <description>Definición del tipo de endoso que se esta realizando</description>
    <label>Tipo de Endoso</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ZRH_TipoEndoso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_TipoObjeto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoObjeto__c</fullName>
    <description>Guarda el tipo de objeto que se quiere actualizar.</description>
    <label>Tipo de Objeto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Cobertura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_Valor__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Valor__c</fullName>
    <description>Valor del campo o atributo que se quiere actualizar</description>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_ValorCondicion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ValorCondicion__c</fullName>
    <description>Guarda el valor del campo que es condición para actualizar el registro.</description>
    <label>Valor Condición</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_ValorCondicionDos__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ValorCondicionDos__c</fullName>
    <label>Valor Condición Dos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ZRH_TipoEndoso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>E-056</fullName>
        <label>Datos de Cobranza</label>
    </customValue>
    <customValue>
        <fullName>E-033</fullName>
        <label>Datos Cláusulas Especiales</label>
    </customValue>
    <customValue>
        <fullName>E-035</fullName>
        <label>Datos Corredores Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-009</fullName>
        <label>Modif. Datos Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-015</fullName>
        <label>Datos Cond.Coberturas Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-023</fullName>
        <label>Modif. Capital/Renta (Vida)</label>
    </customValue>
    <customValue>
        <fullName>E-042</fullName>
        <label>Datos Asegurabilidad Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-043</fullName>
        <label>Datos Contribución Empresa Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-055</fullName>
        <label>Datos Liquid. Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-101</fullName>
        <label>Datos Grales. Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-102</fullName>
        <label>Datos Tarifa Salud (Tipo/Número Integrantes) Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-103</fullName>
        <label>Datos Tarifa Salud (N° de Integrantes por/Por Tipo de Integrantes por Edad) Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-104</fullName>
        <label>Datos Deduc. por Tramo Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-105</fullName>
        <label>Datos Tarifa Escolaridad Pólizas</label>
    </customValue>
    <description>Definición del tipo de endoso que se esta realizando</description>
    <masterLabel>Tipo de Endoso</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ZRH_BatchProcessEndorsements_TEST.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 17/1/2024
Description  : Class test for class ZRH_BatchProcessEndorsements and ZRH_ProcessEndorsementsController
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda              LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      LEC          17/1/2024         Initial Version
********************************************************************************/
@isTest
public class ZRH_BatchProcessEndorsements_TEST {
    
    private static final String OBJECT_GLOSAS = 'ZRH_Glosas__c';
    private static final String FIELD_TIPO_GLOSA = 'ZRH_TipoDeGlosa__c';
    private static final String OBJECT_QUOTE = 'Quote';
    private static final String OPERATOR_AND = 'AND'; 
    private static final String OPERATOR_OR = 'OR';
    private static final String CODE_GLOSS_STANDARD = 'G-001'; 
    private static final String CODE_GLOSS_CONDITIONAL = 'G-002';
    private static final String SR_ASV_SALUD_NAME = 'ZRH_JSON_SaludASV';
    private static final String SR_SALUD_PG_NAME = 'ZRH_JSON_SaludPG'; 
    private static final String SR_ASV_COBERTURA_NAME = 'ZRH_JSON_CoberturaASV';
    private static final String SR_SALUD_REQ_ASEG_NAME = 'ZRH_JSON_SaludRA';
    private static final String SR_SALUD_DEF_NAME = 'ZRH_JSON_SaludDEF';
    private static final String SR_TARIFA_SALUD_NAME = 'ZRH_JSON_SaludTarifa';
    private static final String SR_TARIFA_SCHOLARSHIP_NAME = 'ZRH_JSON_EscolaridadTarifa';
    private static final String SR_SALUD_PARAM_ASV_NAME = 'ZRH_JSON_SaludParamASV';
    private static final String SR_SALUD_PARAM_REPLACE_NAME = 'ZRH_JSON_SaludParamReplace';
    private static final String SR_SALUD_PARAM_CONDITION_NAME = 'ZRH_JSON_SaludParamCondition';
    private static final String SR_SALUD_PARAM_CONTAINS_NAME = 'ZRH_JSON_SaludParamContains';  
    private static final String NUMBER_FOLIO = '123123-0'; 
    public static final String LIFE_SCHOLARSHIP_PLAN= '501';
    public static final String ENDORSEMENT_TYPE= 'E-056';
    
    
    /**
    *  @Description: Test for the Method processEndorsements
    *  @Autor:       LEC, Deloitte
    *  @Date:        17/1/2024
    */
    @isTest 
    static void processEndorsements() {
        
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);
        StaticResource coberturaASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_COBERTURA_NAME);
        StaticResource saludPG = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_SALUD_PG_NAME);
        StaticResource saludTarifa = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_TARIFA_SALUD_NAME);
        StaticResource escolTarifa = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_TARIFA_SCHOLARSHIP_NAME);
        
        Account testAccount = ZRH_DataFactory.createAccount(true);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);
        Product2 testHealthProduct = ZRH_DataFactory.createHealthProduct(true);
        Product2 testHealthCoverage = ZRH_DataFactory.createProduct(true);
        PricebookEntry testPricebookEntryHealth = ZRH_DataFactory.createPricebookEntry(true, testHealthProduct);
        PricebookEntry testPricebookEntryHealthCoverage = ZRH_DataFactory.createPricebookEntry(true, testHealthCoverage);
        Quote parentQuote = ZRH_DataFactory.createQuote(true, testOpportunity);
        Quote childQuote = ZRH_DataFactory.createChildQuote(true, testOpportunity, parentQuote);
        QuoteLineItem testQuoteLineItemHealthOne = ZRH_DataFactory.createQuoteLineItem(true, childQuote, testHealthProduct, testPricebookEntryHealth, saludASV.Body.toString());
        QuoteLineItem testQuoteLineItemHealthCoverage = ZRH_DataFactory.createQuoteLineItem(true, childQuote, testHealthCoverage, testPricebookEntryHealthCoverage, coberturaASV.Body.toString());
        
        Contract testContract = ZRH_DataFactory.createContract(true, parentQuote, testAccount);
        Contract testContractChild = ZRH_DataFactory.createContract(true, childQuote, testAccount);
        testContractChild.ZRH_ContratoHolding__c = testContract.Id;
            
        ContractGroupPlan cgpOne = ZRH_DataFactory.createContractGroupPlan(true, testContractChild, testQuoteLineItemHealthOne);
        ContractGroupPlan cgpTwo = ZRH_DataFactory.createContractGroupPlan(true, testContractChild, testQuoteLineItemHealthCoverage);
        
        cgpOne.vlocity_ins_fsc__AttributeSelectedValues__c = testQuoteLineItemHealthOne.vlocity_ins__AttributeSelectedValues__c;
        
        
        cgpTwo.ContractGroupParentPlanId  = cgpone.Id;
        cgpTwo.vlocity_ins_fsc__AttributeSelectedValues__c = testQuoteLineItemHealthCoverage.vlocity_ins__AttributeSelectedValues__c;
        update cgpOne;
        update cgpTwo;
        update testContractChild;
        
        
        
        ZRH_MaestroGlosas__c masterGlossOne = ZRH_DataFactory.createMasterGloss(true, 1.0);
        ZRH_MaestroGlosas__c masterGlossTwo = ZRH_DataFactory.createMasterGloss(true, 2.0);
        ZRH_MaestroGlosas__c masterGlossThree = ZRH_DataFactory.createMasterGloss(true, 3.0);
        ZRH_MaestroGlosas__c masterGlossFour = ZRH_DataFactory.createMasterGloss(true, 4.0);
        ZRH_MaestroGlosas__c masterGlossFive = ZRH_DataFactory.createMasterGloss(true, 154.0);
        
        ZRH_Glosas__c testGlosaHealthOne = ZRH_DataFactory.createRateGloss(true, testQuoteLineItemHealthOne.Id);
        ZRH_Glosas__c testGlosaHealthTwo = ZRH_DataFactory.createCoverageGloss(true, testQuoteLineItemHealthOne.Id);
        ZRH_Glosas__c testGlosaHealthThree = ZRH_DataFactory.createGloss(true, testQuoteLineItemHealthOne.Id);
        
        StaticResource saludDEF = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_SALUD_DEF_NAME);
        parentQuote.ZRH_CuentasDEF__c = saludDEF.Body.toString();
        testContract.ZRH_CuentasDEF__c = saludDEF.Body.toString();
        update parentQuote;
        update testContract;
        
        childQuote.ZRH_Holding__c = testAccount.Id;
        testContractChild.ZRH_Holding__c = testAccount.Id;
        update childQuote;
        update testContractChild;
        
        StaticResource saludRA = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_SALUD_REQ_ASEG_NAME);
        testQuoteLineItemHealthOne.ZRH_AtributosRequisitosAsegurabilidad__c = saludRA.Body.toString();
        cgpOne.ZRH_AtributosRequisitosAsegurabilidad__c = saludRA.Body.toString();
        cgpOne.ZRH_EndosoEnviado__c = true;
        cgpOne.ZRH_Folio__c = NUMBER_FOLIO;
        cgpOne.ZRH_Periodo__c = 0;
        cgpOne.ZRH_Tarifa__c = saludTarifa.Body.toString();
        cgpOne.AccountId = testAccount.Id;
        update testQuoteLineItemHealthOne;
        update cgpOne;
        
        testQuoteLineItemHealthCoverage.vlocity_ins__ParentItemId2__c = testQuoteLineItemHealthOne.Id;
        update testQuoteLineItemHealthCoverage;    
        
        StaticResource saludParamASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_SALUD_PARAM_ASV_NAME);
        masterGlossOne.ZRH_Parametros__c = saludParamASV.Body.toString();
        masterGlossOne.ZRH_TipoDeGlosa__c = CODE_GLOSS_STANDARD;
        update masterGlossOne;
        
        StaticResource saludParamCondition = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_SALUD_PARAM_CONDITION_NAME);
        masterGlossTwo.ZRH_Parametros__c = saludParamCondition.Body.toString();
        masterGlossTwo.ZRH_LogicaCondiciones__c = OPERATOR_AND;
        masterGlossTwo.ZRH_TipoDeGlosa__c = CODE_GLOSS_CONDITIONAL;
        update masterGlossTwo;
        
        StaticResource saludParamReplace = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_SALUD_PARAM_REPLACE_NAME);
        masterGlossThree.ZRH_Parametros__c = saludParamReplace.Body.toString();
        masterGlossThree.ZRH_LogicaCondiciones__c = OPERATOR_OR;
        masterGlossThree.ZRH_TipoDeGlosa__c = CODE_GLOSS_CONDITIONAL;
        update masterGlossThree;
        
        StaticResource saludParamContains = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_SALUD_PARAM_CONTAINS_NAME);
        masterGlossFour.ZRH_Parametros__c = saludParamContains.Body.toString();
        masterGlossFour.ZRH_LogicaCondiciones__c = OPERATOR_OR;
        masterGlossFour.ZRH_TipoDeGlosa__c = CODE_GLOSS_CONDITIONAL;
        update masterGlossFour;
        masterGlossFive.ZRH_Parametros__c = saludPG.Body.toString();
        masterGlossFive.ZRH_LogicaCondiciones__c = OPERATOR_AND;
        masterGlossFive.ZRH_TipoDeGlosa__c = CODE_GLOSS_CONDITIONAL;
        update masterGlossFive;
        
        ZRH_SincronizacionEndoso__c endoso = new ZRH_SincronizacionEndoso__c();
        endoso.ZRH_NombreObjeto__c = 'ContractGroupPlan';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreCampo__c = 'ZRH_AtributosBMI__c';
        endoso.ZRH_Valor__c = 'Test';
        endoso.ZRH_TipoCampo__c = 'Campo Salesforce';
        endoso.ZRH_TipoEndoso__c = ENDORSEMENT_TYPE;
        endoso.ZRH_TipoObjeto__c = 'Principal'; // Principal, Cobertura 
        insert endoso;
        
        
        Test.startTest();
        Id batId = Database.executeBatch(new ZRH_BatchProcessEndorsements('Id != null'), 1);
        ZRH_ScheduleProcessEndorsements sc = new ZRH_ScheduleProcessEndorsements(); 
        sc.execute(null);
        System.assertEquals(sc != null, true, 'Working!');
        
        endoso = new ZRH_SincronizacionEndoso__c();
        endoso.ZRH_CampoCondicion__c = '';
        endoso.ZRH_CampoCondicionDos__c = '';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreAtributo__c = 'Test';
        endoso.ZRH_NombreCampo__c = 'vlocity_ins__AttributeSelectedValues__c';
        endoso.ZRH_NombreObjeto__c = 'ContractGroupPlan';
        endoso.ZRH_TipoCampo__c = 'JSON'; //Campo Salesforce, JSON
        endoso.ZRH_TipoEndoso__c = '56';
        endoso.ZRH_TipoObjeto__c = 'Cobertura'; // Principal, Cobertura 
        endoso.ZRH_Valor__c = 'Test';
        endoso.ZRH_ValorCondicion__c = '600';
        endoso.ZRH_ValorCondicionDos__c = '';
        ZRH_ProcessEndorsementsController.processEndorsements(endoso);
        
        endoso.ZRH_CampoCondicion__c = 'ParentescoSalud';
        endoso.ZRH_ValorCondicion__c = 'Titular';
        endoso.ZRH_CampoCondicionDos__c = '';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreAtributo__c = 'EdadSalidaS';
        endoso.ZRH_Valor__c = '1';
        endoso.ZRH_NombreCampo__c = 'ZRH_AtributosRequisitosAsegurabilidad__c';
        endoso.ZRH_NombreObjeto__c = 'ContractGroupPlan';
        endoso.ZRH_TipoCampo__c = 'JSON'; //Campo Salesforce, JSON
        endoso.ZRH_TipoEndoso__c = ENDORSEMENT_TYPE;
        endoso.ZRH_TipoObjeto__c = 'Principal'; // Principal, Cobertura 
        endoso.ZRH_ValorCondicionDos__c = '';
        ZRH_ProcessEndorsementsController.processEndorsements(endoso);
        
        endoso.ZRH_CampoCondicion__c = 'DescTarifaSalud';
        endoso.ZRH_ValorCondicion__c = 'EMPRESA';
        endoso.ZRH_CampoCondicionDos__c = '';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreAtributo__c = 'TarifaSaludPP';
        endoso.ZRH_Valor__c = '1';
        endoso.ZRH_NombreCampo__c = 'ZRH_Tarifa__c';
        endoso.ZRH_NombreObjeto__c = 'ContractGroupPlan';
        endoso.ZRH_TipoCampo__c = 'JSON'; //Campo Salesforce, JSON
        endoso.ZRH_TipoEndoso__c = ENDORSEMENT_TYPE;
        endoso.ZRH_TipoObjeto__c = 'Principal'; // Principal, Cobertura 
        endoso.ZRH_ValorCondicionDos__c = '';
        ZRH_ProcessEndorsementsController.processEndorsements(endoso);
        
        testHealthProduct.ProductCode = LIFE_SCHOLARSHIP_PLAN;
        update testHealthProduct;
        
        
        cgpOne.ZRH_Tarifa__c = escolTarifa.Body.toString();
        update cgpOne;
        
        endoso.ZRH_CampoCondicion__c = 'DescripcionNivel';
        endoso.ZRH_ValorCondicion__c = 'SIN NIVEL ESCOLARIDAD';
        endoso.ZRH_CampoCondicionDos__c = 'CodigoCobertura';
        endoso.ZRH_ValorCondicionDos__c = '80';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreAtributo__c = 'PrimaMensualEsc';
        endoso.ZRH_Valor__c = '1';
        endoso.ZRH_NombreCampo__c = 'ZRH_Tarifa__c';
        endoso.ZRH_NombreObjeto__c = 'ContractGroupPlan';
        endoso.ZRH_TipoCampo__c = 'JSON'; //Campo Salesforce, JSON
        endoso.ZRH_TipoEndoso__c = ENDORSEMENT_TYPE;
        endoso.ZRH_TipoObjeto__c = 'Principal'; // Principal, Cobertura
        ZRH_ProcessEndorsementsController.processEndorsements(endoso); 
        
        
        endoso.ZRH_CampoCondicion__c = '';
        endoso.ZRH_ValorCondicion__c = '';
        endoso.ZRH_CampoCondicionDos__c = '';
        endoso.ZRH_ValorCondicionDos__c = '';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreAtributo__c = '';
        endoso.ZRH_Valor__c = '1';
        endoso.ZRH_NombreCampo__c = 'ZRH_AtributosAsistenciasSeleccionados__c';
        endoso.ZRH_NombreObjeto__c = 'Contract';
        endoso.ZRH_TipoCampo__c = 'Campo Salesforce'; //Campo Salesforce, JSON
        endoso.ZRH_TipoEndoso__c = ENDORSEMENT_TYPE;
        endoso.ZRH_TipoObjeto__c = 'Principal'; // Principal, Cobertura
        ZRH_ProcessEndorsementsController.processEndorsements(endoso); 
        
        
        endoso.ZRH_CampoCondicion__c = 'Campo';
        endoso.ZRH_ValorCondicion__c = 'C = Comisiones Pagadas';
        endoso.ZRH_CampoCondicionDos__c = 'Planes';
        endoso.ZRH_ValorCondicionDos__c = '600';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreAtributo__c = 'Valor';
        endoso.ZRH_Valor__c = '1';
        endoso.ZRH_NombreCampo__c = 'ZRH_CuentasDEF__c';
        endoso.ZRH_NombreObjeto__c = 'Contract';
        endoso.ZRH_TipoCampo__c = 'JSON'; //Campo Salesforce, JSON
        endoso.ZRH_TipoEndoso__c = ENDORSEMENT_TYPE;
        endoso.ZRH_TipoObjeto__c = 'Principal'; // Principal, Cobertura
        ZRH_ProcessEndorsementsController.processEndorsements(endoso); 
        
        endoso.ZRH_CampoCondicion__c = 'Campo';
        endoso.ZRH_ValorCondicion__c = 'C = Comisiones Pagadas';
        endoso.ZRH_CampoCondicionDos__c = 'Planes';
        endoso.ZRH_ValorCondicionDos__c = '600';
        endoso.ZRH_Folio__c = NUMBER_FOLIO;
        endoso.ZRH_NombreAtributo__c = 'Valor';
        endoso.ZRH_Valor__c = 'false';
        endoso.ZRH_NombreCampo__c = 'vlocity_ins__Disclosure3__c';
        endoso.ZRH_NombreObjeto__c = 'Account';
        endoso.ZRH_TipoCampo__c = 'Campo Salesforce'; //Campo Salesforce, JSON
        endoso.ZRH_TipoEndoso__c = ENDORSEMENT_TYPE;
        endoso.ZRH_TipoObjeto__c = 'Principal'; // Principal, Cobertura
        ZRH_ProcessEndorsementsController.processEndorsements(endoso); 
        
        endoso.Id = null;
        endoso.ZRH_Estado__c = 'Error';
        insert endoso;
        ZRH_BatchProcessEndorsements.deleteRecords('ZRH_Estado__c = \'Error\'');
        Test.stopTest();
    }

}