force-app/main/default/objects/Product2/fields/vlocity_ins__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salud</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins__RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__RecordTypeName__c</fullName>
    <description>Name of Quote Record Type</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
                <default>true</default>
                <label>New Business</label>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_AtributosSobreprimasSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosSobreprimasSeleccionados__c</fullName>
    <label>Atributos Sobreprimas Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CotizacionHolding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CotizacionHolding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Holding</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Cotizaciones Relacionadas</relationshipLabel>
    <relationshipName>ZRH_CotizacionHolding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_VigenciaInicio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_VigenciaInicio__c</fullName>
    <description>Vigencia inicio</description>
    <label>Vigencia Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_VigenciaTermino__c.field-meta.xml
<CustomField>
    <fullName>ZRH_VigenciaTermino__c</fullName>
    <description>Vigencia Término</description>
    <label>Vigencia Término</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__AttributeSelectedValues__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__AttributeSelectedValues__c</fullName>
    <label>Attribute Selected Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__ParentItemId2__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__ParentItemId2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Item Id</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items (Parent Item Id)</relationshipLabel>
    <relationshipName>ParentItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__ProductChildItemId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__ProductChildItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Child Item</label>
    <referenceTo>vlocity_ins__ProductChildItem__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__ProductName__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__ProductName__c</fullName>
    <formula>Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__RecordTypeName__c</fullName>
    <formula>Product2.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Type__c</fullName>
    <formula>Text(Product2.vlocity_ins__Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_AtributosBMI__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosBMI__c</fullName>
    <label>Atributos BMI</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_AtributosConvenios__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosConvenios__c</fullName>
    <label>Atributos Convenios</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_NumeroDePlanesEnContratantes__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroDePlanesEnContratantes__c</fullName>
    <description>Indica para el plan del holding, cuantos planes en contratantes de este tipo y tarifa existen. Usado para controlar la creación de tarifas.</description>
    <label>Número de Planes en Contratantes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_TarifaModificada__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TarifaModificada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tarifa Modificada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_TipoTarifa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoTarifa__c</fullName>
    <label>Tipo Tarifa</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_TipoTarifaPrevia__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoTarifaPrevia__c</fullName>
    <label>Tipo Tarifa Previa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZRH_QuoteLineItemsSelector.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 27/09/2023
Description  : Query factory for StaticResorces using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda.             LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO			27/09/2023		initial version
********************************************************************************/
public class ZRH_QuoteLineItemsSelector extends fflib_SObjectSelector {
	
    public Schema.SObjectType getSObjectType() {
        return QuoteLineItem.sObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            	QuoteLineItem.Id,
                QuoteLineItem.Product2Id,
                QuoteLineItem.QuoteId,
                QuoteLineItem.ZRH_AtributosRequisitosAsegurabilidad__c,
                QuoteLineItem.ZRH_AtributosBMI__c,
                QuoteLineItem.ZRH_Tarifa__c,
                QuoteLineItem.ZRH_TarifaModificada__c,
                QuoteLineItem.ZRH_TipoTarifa__c,
                QuoteLineItem.ZRH_TipoTarifaPrevia__c,
                QuoteLineItem.ZRH_AtributosReqMedicosSeleccionado__c,
                QuoteLineItem.ZRH_CodigoProducto__c,
                QuoteLineItem.ZRH_AtributosConvenios__c,
                QuoteLineItem.vlocity_ins__AttributeSelectedValues__c,
                QuoteLineItem.vlocity_ins__ParentItemId2__c,
                QuoteLineItem.vlocity_ins__ProductChildItemId__c,
                QuoteLineItem.vlocity_ins__ProductName__c,
                QuoteLineItem.vlocity_ins__RecordTypeName__c,
                QuoteLineItem.ZRH_NumeroDePlanesEnContratantes__c
            };
    }

    public Map<Id,QuoteLineItem> selectProductsBySetIds(Set<ID> idSet){
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField('Quote.ZRH_AtributosSobreprimasSeleccionados__c');
        query.setCondition('vlocity_ins__RecordTypeName__c  = \'Product\' AND QuoteId IN :idSet');
        query.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return new Map<Id,QuoteLineItem>((List<QuoteLineItem>) Database.query(query.toSOQL()));
    }

    
    public List<QuoteLineItem> selectCoverageBySetIds(Set<ID> idSet){
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.setCondition('QuoteId IN :idSet');
        query.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<QuoteLineItem>) Database.query(query.toSOQL());
    }
    
    public List<QuoteLineItem> selectByQuoteId(Set<ID> idSet) {
        return (List<QuoteLineItem>) Database.query(
            newQueryFactory(false, false, true)
            .selectField(QuoteLineItem.Id)    
            .selectField(QuoteLineItem.QuoteId)    
            .selectField(QuoteLineItem.Product2Id)
            .selectField(QuoteLineItem.vlocity_ins__AttributeSelectedValues__c)
            .selectField(QuoteLineItem.vlocity_ins__ParentItemId2__c)
            .selectField(QuoteLineItem.vlocity_ins__ProductChildItemId__c)
            .selectField('Product2.vlocity_ins__RecordTypeName__c')
            .selectField('Product2.Name')
            .selectField('Product2.ProductCode')   
            .selectField('Quote.ZRH_VigenciaInicio__c')   
            .selectField('Quote.ZRH_VigenciaTermino__c')   
            .setCondition('QuoteId IN :idSet')
            .addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING)
            .toSOQL()
        );
    }

    public Database.QueryLocator selectChildAccountRootQLIsByParentQuoteId(Id quoteId) {      
        return Database.getQueryLocator(
            newQueryFactory(false, false, true)
            .selectField(QuoteLineItem.Id)
            .selectField(QuoteLineItem.ZRH_Tarifa__c)
            .selectField(QuoteLineItem.ZRH_TipoTarifa__c)
            .selectField(QuoteLineItem.Product2Id)
            .selectField(QuoteLineItem.PricebookEntryId)
            .selectField(QuoteLineItem.vlocity_ins__ParentItemId2__c)
            .selectField('Product2.vlocity_ins__Type__c')
            .selectField('Product2.ProductCode')
            .selectField('Quote.ZRH_CotizacionHolding__c')
            .setCondition('Quote.ZRH_CotizacionHolding__c =: quoteId AND Product2.RecordType.DeveloperName = \'Product\' AND ZRH_TipoTarifa__c != null')
            .toSOQL()
        );
    }

    public List<QuoteLineItem> selectChildRootQLIsByParentQuoteId(Id quoteId) {      
        return (List<QuoteLineItem>) Database.query(
            newQueryFactory(false, false, true)
            .selectField(QuoteLineItem.Id)
            .selectField(QuoteLineItem.ZRH_Tarifa__c)
            .selectField(QuoteLineItem.ZRH_TipoTarifa__c)
            .selectField(QuoteLineItem.Product2Id)
            .selectField(QuoteLineItem.PricebookEntryId)
            .selectField(QuoteLineItem.vlocity_ins__ParentItemId2__c)
            .selectField(QuoteLineItem.ZRH_TipoTarifaPrevia__c)
            .selectField(QuoteLineItem.ZRH_TarifaModificada__c)
            .selectField('Product2.vlocity_ins__Type__c')
            .selectField('Product2.ProductCode')
            .selectField('Quote.ZRH_CotizacionHolding__c')
            .setCondition('Quote.ZRH_CotizacionHolding__c =: quoteId AND Product2.RecordType.DeveloperName = \'Product\' AND ZRH_TipoTarifa__c != null')
            .toSOQL()
        );
    }

    public List<QuoteLineItem> selectById(Id quoteId) {
        return (List<QuoteLineItem>) Database.query(
            newQueryFactory(false, false, true)
            .selectField(QuoteLineItem.Id)
            .selectField(QuoteLineItem.ZRH_Tarifa__c)
            .selectField(QuoteLineItem.ZRH_TipoTarifa__c)
            .selectField(QuoteLineItem.Product2Id)
            .selectField(QuoteLineItem.PricebookEntryId)
            .selectField(QuoteLineItem.vlocity_ins__ParentItemId2__c)
            .selectField(QuoteLineItem.ZRH_NumeroDePlanesEnContratantes__c)
            .selectField('Product2.ProductCode')
            .selectField('Product2.Name')
            .selectField('Product2.vlocity_ins__Type__c') 
            .selectField('Quote.ZRH_CotizacionHolding__c')
            .selectField('Quote.ZRH_VigenciaInicio__c')   
            .selectField('Quote.ZRH_VigenciaTermino__c')   
            .setCondition('QuoteId =: quoteId')
            .toSOQL()
        );        
    }
    
    /**
    *  @Description: Perform a query with the default fields with the Id of Glosas as a condition
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<QuoteLineItem> selectByIdAndCoverages(String recordId, List<String> fieldList) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField('Product2.Name');
        for(String field: fieldList){
            query.selectField(field);
        }
        query.setCondition('Id = :recordId OR vlocity_ins__ParentItemId2__c = :recordId');
        query.addOrdering('vlocity_ins__ParentItemId2__c', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<QuoteLineItem>) Database.query( query.toSOQL() );
    }
    
    
    /**
    *  @Description: Make a query by quote item, receiving a list as a parameter.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<QuoteLineItem> selectByIdsList(List<String> recordList) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.setCondition('Id in :recordList');
        return (List<QuoteLineItem>) Database.query( query.toSOQL() );
    }
}