force-app/main/default/objects/Account/fields/GLBP1_Rut__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Rut__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Digite el Rut sin puntos, con guión, ejemplo: 12345678-9</inlineHelpText>
    <label>Rut</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZRH_Rut__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Rut__c</fullName>
    <description>RUT para la cuenta business account y cuenta Agency/Brokerage</description>
    <externalId>true</externalId>
    <inlineHelpText>El formato del RUT debe ser 99999999-9</inlineHelpText>
    <label>RUT</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GLBP1_Beneficiario_de_Poliza__c/GLBP1_Beneficiario_de_Poliza__c.object-meta.xml
<CustomObject>
    <label>Beneficiario de Póliza</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiarios de Póliza</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GLBP1_Beneficiario_de_Poliza__c/fields/GLB_P1_NombrePoliza__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_NombrePoliza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre de Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Beneficiario de Póliza</relationshipLabel>
    <relationshipName>Beneficiarios_de_poliza</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GLBP1_Beneficiario_de_Poliza__c/fields/GLB_P1_Parentesco__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_Parentesco__c</fullName>
    <label>Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cónyuge</fullName>
            </value>
            <value>
                <fullName>Hermana</fullName>
            </value>
            <value>
                <fullName>Hermano</fullName>
            </value>
            <value>
                <fullName>Hija</fullName>
            </value>
            <value>
                <fullName>Hijo</fullName>
            </value>
            <value>
                <fullName>Madre</fullName>
            </value>
            <value>
                <fullName>Padre</fullName>
            </value>
            <value>
                <fullName>Pareja</fullName>
            </value>
            <value>
                <fullName>P1</fullName>
                <isActive>false</isActive>
                <label>P1</label>
            </value>
            <value>
                <fullName>P2</fullName>
                <isActive>false</isActive>
                <label>P2</label>
            </value>
            <value>
                <fullName>P3</fullName>
                <isActive>false</isActive>
                <label>P3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GLBP1_Beneficiario_de_Poliza__c/fields/GLB_P1_Rut__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_Rut__c</fullName>
    <label>Rut</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GLBP1_Beneficiario_de_Poliza__c/fields/GLB_P1_Sexo__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Ninguno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GLBP1_Plan_de_pago__c/GLBP1_Plan_de_pago__c.object-meta.xml
<CustomObject>
    <label>Plan de pago</label>
    <nameField>
        <label>Nombre de Plan de pago</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GLBP1_Plan_de_pago__c/fields/GLBP1_Cliente__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planes de pago</relationshipLabel>
    <relationshipName>Planes_de_pago</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GLBP1_Plan_de_pago__c/fields/GLBP1_Direcci_n_de_cobranza__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Direcci_n_de_cobranza__c</fullName>
    <label>Dirección de cobranza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GLBP1_Plan_de_pago__c/fields/GLBP1_Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Forma_de_pago__c</fullName>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Crédito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GLBP1_Plan_de_pago__c/fields/GLBP1_Poliza_de_seguro__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Poliza_de_seguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Póliza de seguro</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Planes de pago (Póliza de seguro)</relationshipLabel>
    <relationshipName>Planes_de_pago1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/GLB_P1_NumeroPolizaExterno__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_NumeroPolizaExterno__c</fullName>
    <externalId>true</externalId>
    <label>Número de póliza externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/GLB_P1_NumeroPolizaExterno__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_NumeroPolizaExterno__c</fullName>
    <label>Número de póliza externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/API_Poliza_GLB_TEST.cls
@isTest
public with sharing class API_Poliza_GLB_TEST {

    @TestSetup
    static void testSetup(){
        Account a = new Account(
            Name = 'TEST ACCOUNT',
            GLBP1_Rut__c = '65155524-8'
        );

        insert a;
        
        Contact c = new Contact(
            FirstName = 'TEST CONTACT',
            lastName = 'TEST CONTACT',
            Accountid = a.Id
        );

        insert c;
    }

    @isTest
    public static void POST_API_TEST_FAIL_VOID_RELATIONSHIPS() {
        

        API_Poliza_GLB.API_POST_POLIZA_WRAPPER mockData = new API_Poliza_GLB.API_POST_POLIZA_WRAPPER();
        mockData.poliza = new InsurancePolicy(
            GLB_P1_NumeroPolizaExterno__c= 'P000003',
            IntermediaryAccount = new Account(GLBP1_Rut__c = '65155524-8'),
            PolicyDescription= 'Descripcion de prueba',
            Status= 'Active',
            PremiumAmount= 10000.00,
            PremiumFrequency= 'Monthly',
            Name='P000003',
            NameInsured = new Account(GLBP1_Rut__c = '65155524-8'),
            PolicyType = 'Auto'
        );
        mockData.planesDePago = new List<GLBP1_Plan_de_pago__c>();
        mockData.activosDePoliza = new List<InsurancePolicyAsset>();
        mockData.beneficiariosDePoliza = new List<GLBP1_Beneficiario_de_Poliza__c>();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/poliza';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response= res;

        Test.startTest();

        API_Poliza_GLB.createPoliza(mockData);

        Test.stopTest();
    }

    @isTest
    public static void POST_API_TEST_FAIL_VOID_ID() {
        

        API_Poliza_GLB.API_POST_POLIZA_WRAPPER mockData = new API_Poliza_GLB.API_POST_POLIZA_WRAPPER();
        mockData.poliza = new InsurancePolicy(
            GLB_P1_NumeroPolizaExterno__c= '',
            IntermediaryAccount = new Account(GLBP1_Rut__c = '65155524-8'),
            PolicyDescription= 'Descripcion de prueba',
            Status= 'Active',
            PremiumAmount= 10000.00,
            PremiumFrequency= 'Monthly',
            Name='P000003',
            NameInsured = new Account(GLBP1_Rut__c = '65155524-8'),
            PolicyType = 'Auto'
        );
        mockData.planesDePago = new List<GLBP1_Plan_de_pago__c>();
        mockData.activosDePoliza = new List<InsurancePolicyAsset>();
        mockData.beneficiariosDePoliza = new List<GLBP1_Beneficiario_de_Poliza__c>();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/poliza';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response= res;

        Test.startTest();

        API_Poliza_GLB.createPoliza(mockData);

        Test.stopTest();
    }

    @isTest
    public static void POST_API_TEST_SUCCESS() {
        String recordTypeIdBS = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesBusiness').getRecordTypeId();
        Account a = new Account(
            Name = 'TEST ACCOUNT',
            ZRH_Rut__c = '65155524-8'
        );

        //insert a;

        a = [Select Id, GLBP1_Rut__c from Account where  Name = 'TEST ACCOUNT'];
        a.RecordTypeId = recordTypeIdBS;
        update a;
        

        API_Poliza_GLB.API_POST_POLIZA_WRAPPER mockData = new API_Poliza_GLB.API_POST_POLIZA_WRAPPER();
        mockData.poliza = new InsurancePolicy(
            GLB_P1_NumeroPolizaExterno__c= 'P000003',
            IntermediaryAccountId = a.Id,
            PolicyDescription= 'Descripcion de prueba',
            Status= 'Active',
            PremiumAmount= 10000.00,
            PremiumFrequency= 'Monthly',
            Name='P000003',
            NameInsuredId = a.Id,
            PolicyType = 'Auto'
        );
        mockData.planesDePago = new List<GLBP1_Plan_de_pago__c>();
        mockData.planesDePago.add(new GLBP1_Plan_de_pago__c(
            GLBP1_Cliente__r = new Account(GLBP1_Rut__c = '65155524-8'),
            GLBP1_Direcci_n_de_cobranza__c = 'Avenida Siempre Viva 123',
            GLBP1_Forma_de_pago__c = 'Contado',
            GLBP1_Poliza_de_seguro__r = new InsurancePolicy(GLB_P1_NumeroPolizaExterno__c = 'P000003'),
            Name = 'Plan de pago de prueba'
        ));
        mockData.activosDePoliza = new List<InsurancePolicyAsset>();
        mockData.activosDePoliza.add(new InsurancePolicyAsset(
            IsActive = true,
            AssetName = 'BMW E36 325I',
            StandardPremiumAmount = 36000.00,
            InsurancePolicy = new InsurancePolicy(GLB_P1_NumeroPolizaExterno__c = 'P000003')
        ));
        mockData.beneficiariosDePoliza = new List<GLBP1_Beneficiario_de_Poliza__c>();
        mockData.beneficiariosDePoliza.add(new GLBP1_Beneficiario_de_Poliza__c(
            GLB_P1_Rut__c = '33333333',
            Name = 'Test Name',
            GLB_P1_Sexo__c = 'Masculino',
            GLB_P1_Parentesco__c = 'Cónyuge',
            GLB_P1_Porcentaje__c = 100,
            GLB_P1_NombrePoliza__r =  new InsurancePolicy(GLB_P1_NumeroPolizaExterno__c = 'P000003')
        ));

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/poliza';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response= res;

        Test.startTest();

        API_Poliza_GLB.createPoliza(mockData);

        Test.stopTest();
    }
}