force-app/main/default/objects/Account/fields/GLBP1_Rut__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Rut__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Digite el Rut sin puntos, con guión, ejemplo: 12345678-9</inlineHelpText>
    <label>Rut</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GLBP1_Participante_de_cotizacion__c/GLBP1_Participante_de_cotizacion__c.object-meta.xml
<CustomObject>
    <label>Participante de cotización</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>N° Participante de cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes de cotización</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GLBP1_Participante_de_cotizacion__c/fields/GLBP1_Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Cotizacion__c</fullName>
    <label>Cotización</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Participantes de cotización</relationshipLabel>
    <relationshipName>Participantes_de_cotizaci_n</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GLBP1_Participante_de_cotizacion__c/fields/GLBP1_Participante__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Participante__c</fullName>
    <label>Participante</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participantes de cotización</relationshipLabel>
    <relationshipName>Participantes_de_cotizaci_n</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/GLBP1_ID_Externo_Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_ID_Externo_Cotizacion__c</fullName>
    <externalId>true</externalId>
    <label>ID externo cotización</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/GLBP1_ID_externo_cotizacion__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_ID_externo_cotizacion__c</fullName>
    <label>ID externo cotización</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/API_Cotizacion_GLB_TEST.cls
@isTest
public with sharing class API_Cotizacion_GLB_TEST {
    @TestSetup
    static void testSetup(){
        Account a = new Account(
            Name = 'TEST ACCOUNT',
            GLBP1_Rut__c = '65155524-8'
        );

        insert a;

        Opportunity o = new Opportunity(
            AccountId = a.Id,
            Name = 'Test Opp',
            StageName = 'Qualification',
            CloseDate = Date.today(),
            OwnerId = UserInfo.getUserId()
        );

        insert o;

        Product2 p = new Product2(Name = 'Test Product');
        insert p;

        PricebookEntry pbe = new PricebookEntry(
            Product2Id = p.Id,
            Pricebook2Id = Test.getStandardPricebookId(),
            UnitPrice = 30.00,
            IsActive = true
        );

        insert pbe;
    }

    @isTest
    public static void POST_API_TEST_FAIL_VOID_RELATIONSHIPS() {
        API_Cotizacion_GLB.API_POST_COTIZACION_WRAPPER mockData = new API_Cotizacion_GLB.API_POST_COTIZACION_WRAPPER();
        mockData.Cotizacion = new Quote(
            GLBP1_ID_Externo_Cotizacion__c = 'TEST01'
        );
        mockData.participantes= new List<GLBP1_Participante_de_cotizacion__c>();
        mockData.partidas = new List<QuoteLineItem>();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/cotizacion';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response = res;

        Test.startTest();

        API_Cotizacion_GLB.createCotizacion(mockData);

        Test.stopTest();
    }

    @isTest
    public static void POST_API_TEST_FAIL_VOID_ID() {
        API_Cotizacion_GLB.API_POST_COTIZACION_WRAPPER mockData = new API_Cotizacion_GLB.API_POST_COTIZACION_WRAPPER();
        mockData.Cotizacion = new Quote(
            GLBP1_ID_Externo_Cotizacion__c = ''
        );
        mockData.participantes= new List<GLBP1_Participante_de_cotizacion__c>();
        mockData.partidas = new List<QuoteLineItem>();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/cotizacion';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response = res;

        Test.startTest();

        API_Cotizacion_GLB.createCotizacion(mockData);

        Test.stopTest();
    }

    @isTest
    public static void POST_API_TEST_SUCCESS() {
        Opportunity o = [
            SELECT Id FROM Opportunity LIMIT 1
        ];

        PricebookEntry pbe = [
            SELECT Id FROM PricebookEntry LIMIT 1
        ];

        API_Cotizacion_GLB.API_POST_COTIZACION_WRAPPER mockData = new API_Cotizacion_GLB.API_POST_COTIZACION_WRAPPER();
        mockData.Cotizacion = new Quote(
            GLBP1_ID_Externo_Cotizacion__c = 'TEST01',
            Name = 'Test Cotizacion',
            OpportunityId = o.Id,
            Pricebook2Id = Test.getStandardPricebookId()
        );
        mockData.participantes = new List<GLBP1_Participante_de_cotizacion__c>();
        mockData.participantes.add(new GLBP1_Participante_de_cotizacion__c(
            GLBP1_Cotizacion__r = new Quote(GLBP1_ID_Externo_Cotizacion__c = 'TEST01'),
            GLBP1_Participante__r = new Account(GLBP1_Rut__c = '65155524-8')
        ));
        mockData.partidas = new List<QuoteLineItem>();
        mockData.partidas.add(new QuoteLineItem(
            Quote = new Quote(GLBP1_ID_Externo_Cotizacion__c = 'TEST01'),
            UnitPrice = 10.00,
            Quantity = 1,
            PricebookEntryId = pbe.Id
        ));

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/cotizacion';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response = res;

        Test.startTest();

        API_Cotizacion_GLB.createCotizacion(mockData);

        Test.stopTest();
    }
}