force-app/main/default/objects/Account/fields/GLBP1_Rut__c.field-meta.xml
<CustomField>
    <fullName>GLBP1_Rut__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Digite el Rut sin puntos, con guión, ejemplo: 12345678-9</inlineHelpText>
    <label>Rut</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GLB_P1_ParticipantePropuesta__c/GLB_P1_ParticipantePropuesta__c.object-meta.xml
<CustomObject>
    <label>Participante propuesta</label>
    <nameField>
        <displayFormat>PART-{00000000}</displayFormat>
        <label>N° Participante de propuesta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes propuesta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GLB_P1_ParticipantePropuesta__c/fields/GLB_P1_NumeroPropuesta__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_NumeroPropuesta__c</fullName>
    <externalId>true</externalId>
    <label>Número de propuesta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GLB_P1_ParticipantePropuesta__c/fields/GLB_P1_Propuesta__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_Propuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propuesta</label>
    <referenceTo>GLB_P1_Propuesta__c</referenceTo>
    <relationshipLabel>Participantes propuesta</relationshipLabel>
    <relationshipName>Participantes_propuesta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GLB_P1_Propuesta__c/GLB_P1_Propuesta__c.object-meta.xml
<CustomObject>
    <label>Propuesta</label>
    <nameField>
        <displayFormat>PRO-{000000}</displayFormat>
        <label>Propuesta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GLB_P1_Propuesta__c/fields/GLB_P1_NumeroPropuesta__c.field-meta.xml
<CustomField>
    <fullName>GLB_P1_NumeroPropuesta__c</fullName>
    <externalId>true</externalId>
    <label>Número de propuesta</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/API_Propuesta_GLB_TEST.cls
@isTest
public with sharing class API_Propuesta_GLB_TEST {
    @TestSetup
    static void testSetup(){
        Account a = new Account(
            Name = 'TEST ACCOUNT',
            GLBP1_Rut__c = '65155524-8'
        );

        insert a;
    }

    @isTest
    public static void POST_API_TEST_FAIL_VOID_RELATIONSHIPS() {
        

        API_Propuesta_GLB.API_POST_PROPUESTA_WRAPPER mockData = new API_Propuesta_GLB.API_POST_PROPUESTA_WRAPPER();
        mockData.propuesta = new GLB_P1_Propuesta__c(
            GLB_P1_NumeroPropuesta__c = 'TEST01'
        );
        mockData.participantes= new List<GLB_P1_ParticipantePropuesta__c>();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/propuesta';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response = res;

        Test.startTest();

        API_Propuesta_GLB.createPropuesta(mockData);

        Test.stopTest();
    }

    @isTest
    public static void POST_API_TEST_FAIL_VOID_ID() {
        

        API_Propuesta_GLB.API_POST_PROPUESTA_WRAPPER mockData = new API_Propuesta_GLB.API_POST_PROPUESTA_WRAPPER();
        mockData.propuesta = new GLB_P1_Propuesta__c(
            GLB_P1_NumeroPropuesta__c = ''
        );
        mockData.participantes = new List<GLB_P1_ParticipantePropuesta__c>();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/propuesta';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response = res;

        Test.startTest();

        API_Propuesta_GLB.createPropuesta(mockData);

        Test.stopTest();
    }

    @isTest
    public static void POST_API_TEST_SUCCESS() {
        

        API_Propuesta_GLB.API_POST_PROPUESTA_WRAPPER mockData = new API_Propuesta_GLB.API_POST_PROPUESTA_WRAPPER();
        mockData.propuesta = new GLB_P1_Propuesta__c(
            GLB_P1_NumeroPropuesta__c = 'TEST01'
        );
        mockData.participantes = new List<GLB_P1_ParticipantePropuesta__c>();
        mockData.participantes.add(new GLB_P1_ParticipantePropuesta__c(
            GLB_P1_Propuesta__r = new GLB_P1_Propuesta__c(GLB_P1_NumeroPropuesta__c = 'TEST01')
        ));


        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();


        req.requestURI = '/services/apexrest/propuesta';  //Request URL

        req.httpMethod = 'POST';//HTTP Request Type

        RestContext.request = req;

        RestContext.response = res;

        Test.startTest();

        API_Propuesta_GLB.createPropuesta(mockData);

        Test.stopTest();
    }
}