force-app/main/default/objects/Account/fields/ZRH_CodigoGrupoNegocio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoGrupoNegocio__c</fullName>
    <description>Código Grupo de Negocio para Cuenta Holding</description>
    <label>Codigo Grupo de Negocio</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZRH_Rut__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Rut__c</fullName>
    <description>RUT para la cuenta business account y cuenta Agency/Brokerage</description>
    <externalId>true</externalId>
    <inlineHelpText>El formato del RUT debe ser 99999999-9</inlineHelpText>
    <label>RUT</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZRH_SucursalRecepcion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_SucursalRecepcion__c</fullName>
    <description>Campo para en listar las sucursales de las oficinas Zurich</description>
    <label>Sucursal Recepción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Santiago</fullName>
            </value>
            <value>
                <fullName>Rancagua</fullName>
            </value>
            <value>
                <fullName>Concepción</fullName>
            </value>
            <value>
                <fullName>Curicó</fullName>
            </value>
            <value>
                <fullName>Viña del Mar</fullName>
            </value>
            <value>
                <fullName>Talca</fullName>
            </value>
            <value>
                <fullName>Los Andes</fullName>
            </value>
            <value>
                <fullName>La Serena</fullName>
            </value>
            <value>
                <fullName>Antofagasta</fullName>
            </value>
            <value>
                <fullName>Puerto Montt</fullName>
            </value>
            <value>
                <fullName>Iquique</fullName>
            </value>
            <value>
                <fullName>Copiapó</fullName>
            </value>
            <value>
                <fullName>Temuco</fullName>
            </value>
            <value>
                <fullName>Osorno</fullName>
            </value>
            <value>
                <fullName>Valdivia</fullName>
            </value>
            <value>
                <fullName>Chillán</fullName>
            </value>
            <value>
                <fullName>Punta Arenas</fullName>
            </value>
            <value>
                <fullName>Los Ángeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/ZRH_AtributosSobreprimasSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosSobreprimasSeleccionados__c</fullName>
    <label>Atributos Sobreprimas Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ZRH_ComisionCorredor__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ComisionCorredor__c</fullName>
    <description>Valor en porcentaje de la comisión del corredor</description>
    <label>Comisión Corredor</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ZRH_Holding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Holding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo relación a cuenta Holding</description>
    <label>Holding</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos (Holding)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/vlocity_ins_fsc__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins_fsc__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracted Plans</relationshipLabel>
    <relationshipName>OrderProductStd</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_AtributosReqMedicosSeleccionado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosReqMedicosSeleccionado__c</fullName>
    <label>Atributos Requistos Medicos Seleccionado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_AtributosRequisitosAsegurabilidad__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosRequisitosAsegurabilidad__c</fullName>
    <description>Se almacena los atributos gestionados de Requisitos de Asegurabilidad.</description>
    <label>Atributos Requisitos de Asegurabilidad.</label>
    <length>98304</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_AtributosTopes__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosTopes__c</fullName>
    <label>Atributos Topes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>vlocity_ins_fsc__Product2Id__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_EsRenovacion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_EsRenovacion__c</fullName>
    <description>Es una póliza de renovación</description>
    <formula>ZRH_Periodo__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renovación</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Estado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Ingresada</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Póliza Reservada e Ingresada</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Envio de propuesta de Poliza al AS400</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Póliza en estado de propuesta sin Error</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Póliza en estado de propuesta con Error</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Póliza en estado de propuesta modificada sin Validar</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Póliza Oficializada</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Anulada</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>No Existe</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Póliza en Curso</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Póliza no Vigente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_GrupoDeCobertura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoDeCobertura__c</fullName>
    <formula>TEXT(vlocity_ins_fsc__Product2Id__r.ZRH_GrupoDeCobertura__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grupo de Cobertura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_NumeroDePoliza__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroDePoliza__c</fullName>
    <formula>IF(ZRH_Folio__c != &quot;&quot;, ZRH_Folio__c + &quot;-&quot; + TEXT(ZRH_Periodo__c), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número de Póliza</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Periodo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Periodo__c</fullName>
    <label>Período</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Tarifa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Tarifa__c</fullName>
    <description>Campo para almacenar la tarifa</description>
    <label>Tarifa</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/vlocity_ins__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salud</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ZRH_GrupoDeCobertura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoDeCobertura__c</fullName>
    <label>Grupo de Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>HOSPITALIZACIONES</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>MATERNIDAD</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AMBULATORIO</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>DENTAL</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>OTRAS PRESTACIONES</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>VIDA</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>PRESTACIONES EN CONVENIO</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>GRUPO PSIQUIATRIA Y PSICOLOGIA</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>CONV.CLINICA DAVILA/HOSP.CLINICO U.CHILE</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>ONCOLOGIA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins__AgencyBrokerageId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__AgencyBrokerageId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency/Brokerage</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins_fsc__GroupCensusStdId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins_fsc__GroupCensusStdId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Census</label>
    <referenceTo>GroupCensus</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_AtributosSobreprimasSeleccionados__c.field-meta.xml
<CustomField>
    <fullName>ZRH_AtributosSobreprimasSeleccionados__c</fullName>
    <label>Atributos Sobreprimas Seleccionados</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_ComisionCorredor__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ComisionCorredor__c</fullName>
    <description>Valor en porcentaje de la comisión del corredor</description>
    <label>Comisión Corredor</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_EjecutivoPropietario__c.field-meta.xml
<CustomField>
    <fullName>ZRH_EjecutivoPropietario__c</fullName>
    <description>Indica el ejecutivo propietario de esta cotización</description>
    <formula>Opportunity.Owner.FirstName&amp;&quot; &quot;&amp;Opportunity.Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ejecutivo Propietario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_Holding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Holding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo relación a cuenta Holding</description>
    <label>Holding</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Holding)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_NombreCorredor__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreCorredor__c</fullName>
    <formula>vlocity_ins__AgencyBrokerageId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Corredor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <externalId>true</externalId>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_GrupoDeCobertura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoDeCobertura__c</fullName>
    <formula>TEXT(Product2.ZRH_GrupoDeCobertura__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grupo de Cobertura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_Periodo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Periodo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Período</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_TipoTarifa__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoTarifa__c</fullName>
    <label>Tipo Tarifa</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZRH_ContractGroupPlansSelector.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 17/11/2023
Description  : Query factory for ContractGroupPlan using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda.             LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO			17/11/2023		initial version
********************************************************************************/
public class ZRH_ContractGroupPlansSelector extends fflib_SObjectSelector{
    
    
    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public Schema.SObjectType getSObjectType(){
        return ContractGroupPlan.sObjectType;
    }
    
    /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            ContractGroupPlan.Id,
                ContractGroupPlan.EffectiveStartDate,
                ContractGroupPlan.EffectiveEndDate,
                ContractGroupPlan.Name,
                ContractGroupPlan.ZRH_Folio__c,
                ContractGroupPlan.ZRH_NumeroDePoliza__c,
                ContractGroupPlan.ZRH_AtributosTopes__c,
                ContractGroupPlan.ZRH_AtributosRequisitosAsegurabilidad__c,
                ContractGroupPlan.ZRH_AtributosReqMedicosSeleccionado__c,
                ContractGroupPlan.ZRH_Tarifa__c,
                ContractGroupPlan.ZRH_TipoTarifa__c,
                ContractGroupPlan.vlocity_ins_fsc__AttributeSelectedValues__c,
                ContractGroupPlan.ZRH_Estado__c,
                ContractGroupPlan.ZRH_CodigoProducto__c,
                ContractGroupPlan.ZRH_Periodo__c,
                ContractGroupPlan.ZRH_EsRenovacion__c,
                ContractGroupPlan.QuoteLineItemId,
                ContractGroupPlan.ContractGroupParentPlanId,
                ContractGroupPlan.vlocity_ins_fsc__Product2Id__c
                };
                    }
    
    /**
    *  @Description: Perform a query by the Id and receiving the fields to which you want to query.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public Database.QueryLocator selectByDynamicCondition(String queryCondition) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField('Contract.Account.Name');
        query.selectField('Contract.Account.ZRH_SucursalRecepcion__c');
        query.selectField('Contract.Account.ShippingAddress');
        query.selectField('Contract.Account.ShippingCity');
        query.selectField('Contract.Account.ShippingState');
        query.selectField('Contract.Account.ZRH_Rut__c');
        query.selectField('Contract.Status');
        query.selectField('Contract.StartDate');
        query.selectField('Contract.EndDate');
        query.selectField('Contract.vlocity_ins__EnrollmentEndDate__c');
        query.selectField('Contract.OwnerId');
        query.selectField('Contract.Owner.Name');
        query.selectField('Contract.CurrencyIsoCode');
        query.selectField('Contract.Owner.ZRH_Rut__c');
        query.selectField('Contract.ZRH_ComisionCorredor__c');
        query.selectField('Contract.SourceQuoteId');
        query.selectField('Contract.SourceQuote.ZRH_EjecutivoPropietario__c');
        query.selectField('Contract.ZRH_NombreCorredor__c');
        query.selectField('Contract.ZRH_ComisionCorredor__c');
        query.selectField('Contract.SourceQuote.QuoteNumber');
        query.selectField('Contract.SourceQuote.vlocity_ins_fsc__GroupCensusStdId__c');
        query.selectField('Contract.vlocity_ins__AgencyBrokerageId__r.ZRH_Rut__c');
        query.selectField('Contract.ZRH_AtributosSobreprimasSeleccionados__c');
        query.selectField('Contract.ZRH_Holding__r.ZRH_CodigoGrupoNegocio__c');
        query.selectField('Contract.ZRH_Holding__r.Name');
        query.selectField('Contract.SourceQuote.Opportunity.Owner.ZRH_Rut__c');
        query.selectField('vlocity_ins_fsc__Product2Id__r.Name');
        query.setCondition(queryCondition);
        
        fflib_QueryFactory rsQF = query.subSelectQuery('ChildContractGroupPlans')
            .selectField('Name')
            .selectField('vlocity_ins_fsc__AttributeSelectedValues__c')
            .selectField('ZRH_CodigoProducto__c')
            .selectField('ZRH_GrupoDeCobertura__c')
            .selectField('vlocity_ins_fsc__Product2Id__r.vlocity_ins__AttributeDefaultValues__c')
            .selectField('vlocity_ins_fsc__Product2Id__r.Name')
            .addOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING);
        
        return Database.getQueryLocator(query.toSOQL());
    }
    
    /**
    *  @Description: Make a query for a holding Quote
    *  @Autor:       ML, Deloitte, mlongg@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<ContractGroupPlan> selectByRelatedQuotes(Set<Id> quoteIds) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(ContractGroupPlan.Id);
        query.selectField(ContractGroupPlan.ContractGroupParentPlanId);
        query.selectField(ContractGroupPlan.Name);
        query.selectField(ContractGroupPlan.vlocity_ins_fsc__Product2Id__c);
        query.selectField(ContractGroupPlan.vlocity_ins_fsc__AttributeSelectedValues__c);
        query.selectField('Contract.EndDate');
        query.selectField('Contract.SourceQuoteId');
        query.selectField('vlocity_ins_fsc__Product2Id__r.vlocity_ins__Type__c');
        query.setCondition('QuoteLineItem.QuoteId IN :quoteIds');
        return (List<ContractGroupPlan>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Perform a query to the ContractGroupPlan by the Id of the ContractGroupPlan.
    *  @Autor:       Jean Nieto, Deloitte, jnieto@deloitte.com
    *  @Date:        14/02/2024
    */
    public List<ContractGroupPlan> selectContractGroupPlanById(Id ContractGroupPlanId) {      
        return (List<ContractGroupPlan>) Database.query(
            newQueryFactory(false, false, true)
            .selectField(ContractGroupPlan.Id)
            .selectField(ContractGroupPlan.vlocity_ins_fsc__AttributeSelectedValues__c)
            .selectField('vlocity_ins_fsc__Product2Id__r.vlocity_ins__AttributeMetadata__c')
            .setCondition('Id = :ContractGroupPlanId')
            .toSOQL()
        );
    }
    
    
    /**
    *  @Description: Query for parent plans from list of contracts
    *  @Autor:       ML, Deloitte, mlongg@deloitte.com
    *  @Date:        2/10/2023
    */
    public List<ContractGroupPlan> selectParentPlansByContractIds(Set<Id> contractIds) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(ContractGroupPlan.Id);
        query.setCondition('ContractId IN :contractIds AND ContractGroupParentPlanId = null');
        return (List<ContractGroupPlan>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Query for parent plans from list of policy numbers
    *  @Autor:       ML, Deloitte, mlongg@deloitte.com
    *  @Date:        29/12/2023
    */
    public List<ContractGroupPlan> selectPlansAndCoveragesByPolicyNumbers(Set<String> policyNumbers) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(ContractGroupPlan.Id);
        query.selectField(ContractGroupPlan.ContractGroupParentPlanId);
        query.selectField(ContractGroupPlan.Name);
        query.selectField(ContractGroupPlan.vlocity_ins_fsc__Product2Id__c);
        query.selectField(ContractGroupPlan.vlocity_ins_fsc__AttributeSelectedValues__c);
        query.selectField(ContractGroupPlan.ZRH_NumeroDePoliza__c);
        query.selectField(ContractGroupPlan.ZRH_Folio__c);
        query.selectField('Contract.EndDate');
        query.selectField('Contract.SourceQuoteId');
        query.selectField('vlocity_ins_fsc__Product2Id__r.vlocity_ins__Type__c');
        query.setCondition('ZRH_NumeroDePoliza__c IN :policyNumbers OR ContractGroupParentPlan.ZRH_NumeroDePoliza__c IN :policyNumbers');
        return (List<ContractGroupPlan>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Perform a query with the default fields with the Id of Glosas as a condition
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        5/1/2023
    */
    public List<ContractGroupPlan> selectByIdAndCoverages(String recordId, List<String> fieldList) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField('vlocity_ins_fsc__Product2Id__r.Name');
        for(String field: fieldList){
            query.selectField(field);
        }
        query.setCondition('Id = :recordId OR ContractGroupParentPlanId = :recordId');
        query.addOrdering('ContractGroupParentPlanId', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<ContractGroupPlan>) Database.query( query.toSOQL() );
    }
    
    
    /**
    *  @Description: Perform a query by the Id and receiving ids for policy.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        8/1/2024
    */
    public Database.QueryLocator selectByEndorsementSentTrue() { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.setCondition('ZRH_EndosoEnviado__c = true');
        return Database.getQueryLocator(query.toSOQL());
    }
    
    
    /**
    *  @Description: Perform a query by the Id and receiving ids for policy.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        8/1/2024
    */
    public List<ContractGroupPlan> selectByFolio(String condition, List<String> fieldList) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        for(String field: fieldList){
            query.selectField(field);
        }
        query.setCondition(condition);
        
        fflib_QueryFactory rsQF = query.subSelectQuery('ChildContractGroupPlans')
            .selectField('vlocity_ins_fsc__AttributeSelectedValues__c')
            .selectField('ZRH_CodigoProducto__c')
            .selectField('ZRH_GrupoDeCobertura__c')
            .selectField('vlocity_ins_fsc__Product2Id__r.Name');
        return (List<ContractGroupPlan>) Database.query( query.toSOQL() );
    }

    /**
    *  @Description: Query cgps by source quote ids and record type developer name
    *  @Autor:       Mateo Long, Deloitte, mlongg@deloitte.com
    *  @Date:        20/02/2024
    */
    public List<ContractGroupPlan> selectPlansBySourceQuoteIdAndRecTypeDeveloperName(List<Id> quoteIds, String recordTypeName) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(ContractGroupPlan.Id);
        query.setCondition('Contract.SourceQuoteId IN :quoteIds AND vlocity_ins_fsc__Product2Id__r.RecordType.DeveloperName =: recordTypeName');
        return (List<ContractGroupPlan>) Database.query( query.toSOQL() );
    }
    
    
}