force-app/main/default/objects/Account/fields/ZRH_Rut__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Rut__c</fullName>
    <description>RUT para la cuenta business account y cuenta Agency/Brokerage</description>
    <externalId>true</externalId>
    <inlineHelpText>El formato del RUT debe ser 99999999-9</inlineHelpText>
    <label>RUT</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_NumeroDePoliza__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroDePoliza__c</fullName>
    <formula>IF(ZRH_Folio__c != &quot;&quot;, ZRH_Folio__c + &quot;-&quot; + TEXT(ZRH_Periodo__c), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número de Póliza</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_NumeroDePolizaSinDV__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroDePolizaSinDV__c</fullName>
    <formula>IF(
FIND(&quot;-&quot;, ZRH_Folio__c) &gt; 0,
LEFT(ZRH_Folio__c, FIND(&quot;-&quot;, ZRH_Folio__c) - 1),
ZRH_Folio__c
) + &quot;-&quot; + TEXT(ZRH_Periodo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número de Póliza sin DV</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_ClaveSincronizacion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ClaveSincronizacion__c</fullName>
    <externalId>true</externalId>
    <label>Clave de sincronizacion</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_Rut__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Rut__c</fullName>
    <label>Rut</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_TipoMovimiento__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoMovimiento__c</fullName>
    <label>Tipo de movimiento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inclusión</fullName>
            </value>
            <value>
                <fullName>Exclusión</fullName>
            </value>
            <value>
                <fullName>Modificación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/ZRH_NumeroDePoliza__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroDePoliza__c</fullName>
    <formula>ContractGroupPlan.ZRH_NumeroDePoliza__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número de Póliza</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_ins_fsc__GroupCensusStdId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins_fsc__GroupCensusStdId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Census</label>
    <referenceTo>GroupCensus</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ZRH_CotizacionHolding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CotizacionHolding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Holding</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Cotizaciones Relacionadas</relationshipLabel>
    <relationshipName>ZRH_CotizacionHolding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_ins__ParentItemId2__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__ParentItemId2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Item Id</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items (Parent Item Id)</relationshipLabel>
    <relationshipName>ParentItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <externalId>true</externalId>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZRH_InsurancePolicySelector_TEST.cls
@isTest
public class ZRH_InsurancePolicySelector_TEST {

    private static final String SR_ASV_SALUD_NAME = 'ZRH_JSON_SaludASV';

    @isTest
    public static void selectByPrimaryMembersAndPolicyNumbersTest() {
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);

        Account testAccount = ZRH_DataFactory.createAccount(true);
        GroupClass groupClass = ZRH_DataFactory.createGroupClass(true, testAccount);
        GroupCensus groupCensus = ZRH_DataFactory.createGroupCensus(true, testAccount);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);

        Product2 testLifeProduct = ZRH_DataFactory.createLifeProduct(true);
        PricebookEntry testPricebookEntryLife = ZRH_DataFactory.createPricebookEntry(true, testLifeProduct);
        
        Quote holdingQuote = ZRH_DataFactory.createQuote(true, testOpportunity);
        Quote testQuoteOne = ZRH_DataFactory.createQuote(false, testOpportunity);
        testQuoteOne.vlocity_ins_fsc__GroupCensusStdId__c = groupCensus.Id;
        testQuoteOne.ZRH_CotizacionHolding__c = holdingQuote.Id;
        insert testQuoteOne;
        
        QuoteLineItem testQuoteLineItemOne = ZRH_DataFactory.createQuoteLineItem(false, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());
        testQuoteLineItemOne.ZRH_Folio__c = Math.random() + '1';
        insert testQuoteLineItemOne;
        QuoteLineItem testQuoteLineItemOneCoverage = ZRH_DataFactory.createQuoteLineItem(false, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());
        testQuoteLineItemOneCoverage.vlocity_ins__ParentItemId2__c = testQuoteLineItemOne.Id;
        insert testQuoteLineItemOneCoverage;

        Contract testContract = ZRH_DataFactory.createContract(true, testQuoteOne, testAccount);
        ContractGroupPlan cgpOne = ZRH_DataFactory.createContractGroupPlan(true, testContract, testQuoteLineItemOne);
        ContractGroupPlan cgpOneCoverage = ZRH_DataFactory.createContractGroupPlan(false, testContract, testQuoteLineItemOneCoverage);
        cgpOneCoverage.ContractGroupParentPlanId = cgpOne.Id;
        insert cgpOneCoverage;

        GroupCensusMember primary1 = ZRH_DataFactory.createPrimaryGroupCensusMember(false, groupCensus, groupClass);
        primary1.ZRH_ClaveSincronizacion__c = '123456789';
        primary1.ZRH_TipoMovimiento__c = 'Inclusión';
        primary1.PolicyStartDate = Date.today();
        insert primary1;
        
        Account personAcc1 = ZRH_DataFactory.createPersonAccountWithRUT(true, primary1.ZRH_Rut__c);
        InsurancePolicy insurancePolicy = ZRH_DataFactory.createInsurancePolicy(true, personAcc1.Id, cgpOne.Id);
        InsurancePolicyParticipant ipp = ZRH_DataFactory.createPrimaryInsurancePolicyParticipant(true, insurancePolicy.Id, personAcc1.Id);
        InsurancePolicyCoverage ipc = ZRH_DataFactory.createInsurancePolicyCoverage(true, insurancePolicy.Id, testLifeProduct.Id);

        Set<String> mockPrimaryRuts = new Set<String>{personAcc1.ZRH_Rut__c};
        List<ContractGroupPlan> cgp = [SELECT ZRH_NumeroDePoliza__c FROM ContractGroupPlan WHERE Id = :cgpOne.Id];
        System.debug(cgp);
        Set<String> mockPolicyNumbers = new Set<String>{cgp[0].ZRH_NumeroDePoliza__c};

        Test.startTest();
        List<InsurancePolicy> results = new ZRH_InsurancePolicySelector().selectByPrimaryMembersAndPolicyNumbers(mockPrimaryRuts, mockPolicyNumbers);
        System.assertEquals(1, results.size(), 'selectByPrimaryMembersAndPolicyNumbers method failed to return expected results');
        Test.stopTest();
    }

    @isTest
    public static void selectByPrimaryMembersTest() {
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);

        Account testAccount = ZRH_DataFactory.createAccount(true);
        GroupClass groupClass = ZRH_DataFactory.createGroupClass(true, testAccount);
        GroupCensus groupCensus = ZRH_DataFactory.createGroupCensus(true, testAccount);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);

        Product2 testLifeProduct = ZRH_DataFactory.createLifeProduct(true);
        PricebookEntry testPricebookEntryLife = ZRH_DataFactory.createPricebookEntry(true, testLifeProduct);
        
        Quote holdingQuote = ZRH_DataFactory.createQuote(true, testOpportunity);
        Quote testQuoteOne = ZRH_DataFactory.createQuote(false, testOpportunity);
        testQuoteOne.vlocity_ins_fsc__GroupCensusStdId__c = groupCensus.Id;
        testQuoteOne.ZRH_CotizacionHolding__c = holdingQuote.Id;
        insert testQuoteOne;
        
        QuoteLineItem testQuoteLineItemOne = ZRH_DataFactory.createQuoteLineItem(false, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());
        testQuoteLineItemOne.ZRH_Folio__c = Math.random() + '1';
        insert testQuoteLineItemOne;
        QuoteLineItem testQuoteLineItemOneCoverage = ZRH_DataFactory.createQuoteLineItem(false, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());
        testQuoteLineItemOneCoverage.vlocity_ins__ParentItemId2__c = testQuoteLineItemOne.Id;
        insert testQuoteLineItemOneCoverage;

        Contract testContract = ZRH_DataFactory.createContract(true, testQuoteOne, testAccount);
        ContractGroupPlan cgpOne = ZRH_DataFactory.createContractGroupPlan(true, testContract, testQuoteLineItemOne);
        ContractGroupPlan cgpOneCoverage = ZRH_DataFactory.createContractGroupPlan(false, testContract, testQuoteLineItemOneCoverage);
        cgpOneCoverage.ContractGroupParentPlanId = cgpOne.Id;
        insert cgpOneCoverage;

        GroupCensusMember primary1 = ZRH_DataFactory.createPrimaryGroupCensusMember(false, groupCensus, groupClass);
        primary1.ZRH_ClaveSincronizacion__c = '123456789';
        primary1.ZRH_Rut__c = '123';
        primary1.ZRH_TipoMovimiento__c = 'Inclusión';
        primary1.PolicyStartDate = Date.today();
        insert primary1;

        Account personAcc1 = ZRH_DataFactory.createPersonAccountWithRUT(true, primary1.ZRH_Rut__c);
        InsurancePolicy insurancePolicy = ZRH_DataFactory.createInsurancePolicy(true, personAcc1.Id, cgpOne.Id);
        InsurancePolicyParticipant ipp = ZRH_DataFactory.createPrimaryInsurancePolicyParticipant(true, insurancePolicy.Id, personAcc1.Id);
        InsurancePolicyCoverage ipc = ZRH_DataFactory.createInsurancePolicyCoverage(true, insurancePolicy.Id, testLifeProduct.Id);

        Set<String> primaryRuts = new Set<String>{personAcc1.ZRH_Rut__c};
        Set<Id> quoteIds = new Set<Id>{testQuoteOne.Id};

        Test.startTest();
        List<InsurancePolicy> results = new ZRH_InsurancePolicySelector().selectByPrimaryMembers(primaryRuts, quoteIds);
        System.assertEquals(true, results.size() != null, 'selectByPrimaryMembers method failed to return expected results');
        Test.stopTest();
    }

    @isTest
    public static void selectByPrimaryMemberRutPolicyNumberAndQuoteIdsTest() {
        StaticResource saludASV = new ZRH_StaticResourcesSelector().selectByStaticResourceNameWithLimit(SR_ASV_SALUD_NAME);

        Account testAccount = ZRH_DataFactory.createAccount(true);
        GroupClass groupClass = ZRH_DataFactory.createGroupClass(true, testAccount);
        GroupCensus groupCensus = ZRH_DataFactory.createGroupCensus(true, testAccount);
        Opportunity testOpportunity = ZRH_DataFactory.createOpportunity(true, testAccount);

        Product2 testLifeProduct = ZRH_DataFactory.createLifeProduct(true);
        PricebookEntry testPricebookEntryLife = ZRH_DataFactory.createPricebookEntry(true, testLifeProduct);
        
        Quote holdingQuote = ZRH_DataFactory.createQuote(true, testOpportunity);
        Quote testQuoteOne = ZRH_DataFactory.createQuote(false, testOpportunity);
        testQuoteOne.vlocity_ins_fsc__GroupCensusStdId__c = groupCensus.Id;
        testQuoteOne.ZRH_CotizacionHolding__c = holdingQuote.Id;
        insert testQuoteOne;
        
        QuoteLineItem testQuoteLineItemOne = ZRH_DataFactory.createQuoteLineItem(false, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());
        testQuoteLineItemOne.ZRH_Folio__c = Math.random() + '1';
        insert testQuoteLineItemOne;
        QuoteLineItem testQuoteLineItemOneCoverage = ZRH_DataFactory.createQuoteLineItem(false, testQuoteOne, testLifeProduct, testPricebookEntryLife, saludASV.Body.toString());
        testQuoteLineItemOneCoverage.vlocity_ins__ParentItemId2__c = testQuoteLineItemOne.Id;
        insert testQuoteLineItemOneCoverage;

        Contract testContract = ZRH_DataFactory.createContract(true, testQuoteOne, testAccount);
        ContractGroupPlan cgpOne = ZRH_DataFactory.createContractGroupPlan(true, testContract, testQuoteLineItemOne);
        ContractGroupPlan cgpOneCoverage = ZRH_DataFactory.createContractGroupPlan(false, testContract, testQuoteLineItemOneCoverage);
        cgpOneCoverage.ContractGroupParentPlanId = cgpOne.Id;
        insert cgpOneCoverage;

        GroupCensusMember primary1 = ZRH_DataFactory.createPrimaryGroupCensusMember(false, groupCensus, groupClass);
        primary1.ZRH_ClaveSincronizacion__c = '123456789';
        primary1.ZRH_Rut__c = '123';
        primary1.ZRH_TipoMovimiento__c = 'Inclusión';
        primary1.PolicyStartDate = Date.today();
        insert primary1;

        Account personAcc1 = ZRH_DataFactory.createPersonAccountWithRUT(true, primary1.ZRH_Rut__c);
        InsurancePolicy insurancePolicy = ZRH_DataFactory.createInsurancePolicy(true, personAcc1.Id, cgpOne.Id);
        InsurancePolicyParticipant ipp = ZRH_DataFactory.createPrimaryInsurancePolicyParticipant(true, insurancePolicy.Id, personAcc1.Id);
        InsurancePolicyCoverage ipc = ZRH_DataFactory.createInsurancePolicyCoverage(true, insurancePolicy.Id, testLifeProduct.Id);

        Set<String> primaryRuts = new Set<String>{personAcc1.ZRH_Rut__c};
        List<ContractGroupPlan> cgp = [SELECT ZRH_NumeroDePolizaSinDV__c FROM ContractGroupPlan WHERE Id = :cgpOne.Id];
        Set<String> policyNumbers = new Set<String>{cgp[0].ZRH_NumeroDePolizaSinDV__c};
        Set<Id> quoteIds = new Set<Id>{testQuoteOne.Id};

        Test.startTest();
        List<InsurancePolicy> results = new ZRH_InsurancePolicySelector().selectByPrimaryMemberRutPolicyNumberAndQuoteIds(primaryRuts, policyNumbers, quoteIds);
        System.assertEquals(true, results.size() != null, 'selectByPrimaryMembers method failed to return expected results');
        Test.stopTest();
    }
}