force-app/main/default/objects/Account/fields/ZRH_CodigoGrupoNegocio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoGrupoNegocio__c</fullName>
    <description>Código Grupo de Negocio para Cuenta Holding</description>
    <label>Codigo Grupo de Negocio</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ZRH_ContratoHolding__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ContratoHolding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato Holding</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratos Relacionados</relationshipLabel>
    <relationshipName>ZRH_ContratoHolding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_CodigoProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CodigoProducto__c</fullName>
    <formula>vlocity_ins_fsc__Product2Id__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Estado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Ingresada</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Póliza Reservada e Ingresada</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Envio de propuesta de Poliza al AS400</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Póliza en estado de propuesta sin Error</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Póliza en estado de propuesta con Error</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Póliza en estado de propuesta modificada sin Validar</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Póliza Oficializada</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Anulada</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>No Existe</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Póliza en Curso</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Póliza no Vigente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <label>Folio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_GrupoDeCobertura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoDeCobertura__c</fullName>
    <formula>TEXT(vlocity_ins_fsc__Product2Id__r.ZRH_GrupoDeCobertura__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grupo de Cobertura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_PDFPolizaCreado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_PDFPolizaCreado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PDF Poliza Creado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_Periodo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Periodo__c</fullName>
    <label>Período</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractGroupPlan/fields/ZRH_TipoDeProducto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoDeProducto__c</fullName>
    <formula>vlocity_ins_fsc__Product2Id__r.vlocity_ins__RecordTypeName__c</formula>
    <label>Tipo de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZRH_ContractsSelector.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 17/11/2023
Description  : Query factory for ContractGroupPlan using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda.             LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO			17/11/2023		initial version
********************************************************************************/
public class ZRH_ContractsSelector extends fflib_SObjectSelector{

    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public Schema.SObjectType getSObjectType(){
        return Contract.sObjectType;
    }
    
    /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Contract.Id,
            Contract.Name,
            Contract.AccountId,
            Contract.Status,
            Contract.ContractNumber,
            Contract.ZRH_ContratoHolding__c
        };
    }

    /**
    *  @Description: Perform a query to the contract by the Id of the contract.
    *  @Autor:       Mateo Long, Deloitte, mlongg@deloitte.com
    *  @Date:        24/11/2023
    */
    public List<Contract> selectContractById(Id contractId) {      
        return (List<Contract>) Database.query(
            newQueryFactory(false, false, true)
            .selectField(Contract.Id)
            .setCondition('Id = :contractId')
            .toSOQL()
        );
    }

    /**
    *  @Description: Perform a query to the contract by the Id of the source quote.
    *  @Autor:       Mateo Long, Deloitte, mlongg@deloitte.com
    *  @Date:        24/11/2023
    */
    public List<Contract> selectContractsBySourceQuoteIds(List<Id> sourceQuoteIds) {      
        return (List<Contract>) Database.query(
            newQueryFactory(false, false, true)
            .selectField(Contract.Id)
            .selectField(Contract.ContractNumber)
            .selectField(Contract.ZRH_ContratoHolding__c)
            .selectField('Account.Name')
            .selectField('Account.ZRH_CodigoGrupoNegocio__c')
            .setCondition('SourceQuoteId IN :sourceQuoteIds')
            .toSOQL()
        );
    }
    
    /**
    *  @Description: Perform a query by the Id.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public List<Contract> selectByIds(Id recordId) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField('Account.Name');
        query.selectField('Account.ZRH_CodigoGrupoNegocio__c');
        query.selectField('OwnerId');
        query.selectField('EndDate');
        query.selectField('StartDate');
        query.setCondition('Id = :recordId');
        
        fflib_QueryFactory subQuey = query.subSelectQuery('ContractGroupPlans')
            .selectField('Id')
            .selectField('ZRH_Estado__c')
            .selectField('ZRH_Folio__c') 
            .selectField('ZRH_GrupoDeCobertura__c')
            .selectField('ZRH_PDFPolizaCreado__c')
            .selectField('ZRH_Periodo__c') 
            .setCondition('ZRH_TipoDeProducto__c = \'Product\'');
        
        return (List<Contract>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Perform a query by the AccountIds.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public List<Contract> selectByAccountIds(List<String> accountList) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField('Account.Name');
        query.selectField('OwnerId');
        query.selectField('EndDate');
        query.selectField('StartDate');
        query.setCondition('AccountId in :accountList');
        
        fflib_QueryFactory subQuey = query.subSelectQuery('ContractGroupPlans')
            .selectField('Id')
            .selectField('ZRH_Estado__c')
            .selectField('ZRH_Folio__c') 
            .selectField('ZRH_GrupoDeCobertura__c')
            .selectField('ZRH_PDFPolizaCreado__c')
            .selectField('ZRH_CodigoProducto__c')
            .selectField('ZRH_Periodo__c') 
            .setCondition('ZRH_TipoDeProducto__c = \'Product\'');
        
        return (List<Contract>) Database.query( query.toSOQL() );
    }
    
    /**
    *  @Description: Perform a query by the Id and receiving the fields to which you want to query.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        8/1/2024
    */
    public Contract selectById(String recordId, List<String> fieldList) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        for(String field: fieldList){
            query.selectField(field);
        }
        query.setCondition('Id = :recordId');
        return (Contract) Database.query( query.toSOQL() );
    }
}