force-app/main/default/objects/GroupCensusMember/fields/ZRH_Banco__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>42</fullName>
                <label>AMERICAN EXPRESS BANK LTD</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>BANCO BCI - TBANC</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>BANCO BICE</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>BANCO CENTRAL DE CHILE</label>
            </value>
            <value>
                <fullName>55</fullName>
                <label>BANCO CONSORCIO</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>BANCO DE CHILE</label>
            </value>
            <value>
                <fullName>43</fullName>
                <label>BANCO DE LA NACION ARGENTINA</label>
            </value>
            <value>
                <fullName>507</fullName>
                <label>BANCO DEL DESARROLLO</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>BANCO DO BRASIL S.A.</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>BANCO DRESDNER</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>BANCO ESTADO</label>
            </value>
            <value>
                <fullName>38</fullName>
                <label>BANCO EXTERIOR S.A.</label>
            </value>
            <value>
                <fullName>51</fullName>
                <label>BANCO FALABELLA</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>BANCO INTERNACIONAL</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>BANCO ITAU</label>
            </value>
            <value>
                <fullName>57</fullName>
                <label>BANCO PARIS</label>
            </value>
            <value>
                <fullName>56</fullName>
                <label>BANCO PENTA</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>BANCO RIPLEY</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>BANCO SANTANDER</label>
            </value>
            <value>
                <fullName>49</fullName>
                <label>BANCO SECURITY</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>BANK OF AMERICA</label>
            </value>
            <value>
                <fullName>672</fullName>
                <label>COOPEUCH</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>CORP BANCA</label>
            </value>
            <value>
                <fullName>716</fullName>
                <label>CORPORACION FINANCIERA ATLAS</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>DEUTSCHE BANK</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>HSBC BANK (CHILE)</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>JP MORGAN CHASE BANK, N. A.</label>
            </value>
            <value>
                <fullName>54</fullName>
                <label>RABOBANK</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>SCOTIABANK</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>SERVICIO CAJA SERVIPAG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_CapitalVidaVoluntario__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CapitalVidaVoluntario__c</fullName>
    <label>Capital Vida Voluntario</label>
    <precision>17</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_ClaveSincronizacion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ClaveSincronizacion__c</fullName>
    <externalId>true</externalId>
    <label>Clave de sincronizacion</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_Estado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carga en Proceso</fullName>
            </value>
            <value>
                <fullName>Proceso de Carga Finalizado</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_ExclusionRealizada__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ExclusionRealizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifica si el asegurado ya fue excluido de la póliza</description>
    <label>Exclusión Realizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_FechaConversionCapital__c.field-meta.xml
<CustomField>
    <fullName>ZRH_FechaConversionCapital__c</fullName>
    <label>Fecha conversion capital</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_FechaExclusion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_FechaExclusion__c</fullName>
    <label>Fecha Exclusión</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_InclusionRealizada__c.field-meta.xml
<CustomField>
    <fullName>ZRH_InclusionRealizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifica si el asegurado ya fue inscripto.</description>
    <label>Inclusión Realizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_NivelEscolaridad__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NivelEscolaridad__c</fullName>
    <label>Nivel de escolaridad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>SIN NIVEL ESCOLARIDAD</label>
            </value>
            <value>
                <fullName>PK</fullName>
                <label>PRE KINDER</label>
            </value>
            <value>
                <fullName>KI</fullName>
                <label>KINDER</label>
            </value>
            <value>
                <fullName>1B</fullName>
                <label>PRIMERO BASICO</label>
            </value>
            <value>
                <fullName>2B</fullName>
                <label>SEGUNDO BASICO</label>
            </value>
            <value>
                <fullName>3B</fullName>
                <label>TERCERO BASICO</label>
            </value>
            <value>
                <fullName>4B</fullName>
                <label>CUARTO BASICO</label>
            </value>
            <value>
                <fullName>5B</fullName>
                <label>QUINTO BASICO</label>
            </value>
            <value>
                <fullName>6B</fullName>
                <label>SEXTO BASICO</label>
            </value>
            <value>
                <fullName>7B</fullName>
                <label>SEPTIMO BASICO</label>
            </value>
            <value>
                <fullName>8B</fullName>
                <label>OCTAVO BASICO</label>
            </value>
            <value>
                <fullName>1M</fullName>
                <label>PRIMERO MEDIO</label>
            </value>
            <value>
                <fullName>2M</fullName>
                <label>SEGUNDO MEDIO</label>
            </value>
            <value>
                <fullName>3M</fullName>
                <label>TERCERO MEDIO</label>
            </value>
            <value>
                <fullName>4M</fullName>
                <label>CUARTO MEDIO</label>
            </value>
            <value>
                <fullName>1S</fullName>
                <label>PRIMERO TEC-SUPERIOR 5 AÑOS</label>
            </value>
            <value>
                <fullName>2S</fullName>
                <label>SEGUNDO TEC-SUPERIOR 5 AÑOS</label>
            </value>
            <value>
                <fullName>3S</fullName>
                <label>TERCERO TEC-SUPERIOR 5 AÑOS</label>
            </value>
            <value>
                <fullName>4S</fullName>
                <label>CUARTO TEC-SUPERIOR 5 AÑOS</label>
            </value>
            <value>
                <fullName>5S</fullName>
                <label>QUINTO TEC-SUPERIOR 5 AÑOS</label>
            </value>
            <value>
                <fullName>1Z</fullName>
                <label>PRIMERO SUPERIOR 6 AÑOS</label>
            </value>
            <value>
                <fullName>2Z</fullName>
                <label>SEGUNDO SUPERIOR 6 AÑOS</label>
            </value>
            <value>
                <fullName>3Z</fullName>
                <label>TERCERO SUPERIOR 6 AÑOS</label>
            </value>
            <value>
                <fullName>4Z</fullName>
                <label>CUARTO SUPERIOR 6 AÑOS</label>
            </value>
            <value>
                <fullName>5Z</fullName>
                <label>QUINTO SUPERIOR 6 AÑOS</label>
            </value>
            <value>
                <fullName>6Z</fullName>
                <label>SEXTO SUPERIOR 6 AÑOS</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>PRIMERO SUPERIOR 7 AÑOS</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SEGUNDO SUPERIOR 7 AÑOS</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>TERCERO SUPERIOR 7 AÑOS</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>CUARTO SUPERIOR 7 AÑOS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_NumeroCuentaBancaria__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroCuentaBancaria__c</fullName>
    <label>Numero de cuenta bancaria</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_NumeroRentas__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroRentas__c</fullName>
    <label>Número de Rentas</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_NumeroTelefonoAlternativo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NumeroTelefonoAlternativo__c</fullName>
    <label>Número de teléfono alternativo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_Poliza__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Poliza__c</fullName>
    <description>Indica la poliza a la que el miembro esta relacionado. El campo se carga con el folio mas el periodo</description>
    <label>Póliza</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_Rut__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Rut__c</fullName>
    <label>Rut</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_TipoMovimiento__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoMovimiento__c</fullName>
    <label>Tipo de movimiento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inclusión</fullName>
            </value>
            <value>
                <fullName>Exclusión</fullName>
            </value>
            <value>
                <fullName>Modificación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupCensusMember/fields/ZRH_VigenciaHistorica__c.field-meta.xml
<CustomField>
    <fullName>ZRH_VigenciaHistorica__c</fullName>
    <label>Vigencia Historica</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ZRH_GroupCensusMemberSelector.cls
public inherited sharing class ZRH_GroupCensusMemberSelector extends fflib_SObjectSelector{
    
    public Schema.SObjectType getSObjectType() {
        return GroupCensusMember.sObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                GroupCensusMember.Id,
                GroupCensusMember.PrimaryGroupCensusMemberId,
                GroupCensusMember.GroupClassId,
                GroupCensusMember.RelationshipToPrimaryMember,
                GroupCensusMember.FirstName,
                GroupCensusMember.LastName,
                GroupCensusMember.Name,
                GroupCensusMember.Email,
                GroupCensusMember.Birthdate,
                GroupCensusMember.Gender,
                GroupCensusMember.PhoneNumber,
                GroupCensusMember.Street,
                GroupCensusMember.State,
                GroupCensusMember.City,
                GroupCensusMember.Country,
                GroupCensusMember.PostalCode,
                GroupCensusMember.PolicyStartDate,
                GroupCensusMember.AnnualEligibleSalary,
                GroupCensusMember.ZRH_Banco__c,
                GroupCensusMember.ZRH_Capital__c,
                GroupCensusMember.ZRH_CapitalVidaVoluntario__c,
                GroupCensusMember.ZRH_CodigoMonedaRenta__c,
                GroupCensusMember.ZRH_ClaveSincronizacion__c,
                GroupCensusMember.ZRH_Estado__c,
                GroupCensusMember.ZRH_FechaConversionCapital__c,
                GroupCensusMember.ZRH_NivelEscolaridad__c,
                GroupCensusMember.ZRH_NumeroCuentaBancaria__c,
                GroupCensusMember.ZRH_NumeroRentas__c,
                GroupCensusMember.ZRH_NumeroTelefonoAlternativo__c,
                GroupCensusMember.ZRH_OmitirRequisitosAsegurabilidad__c,
                GroupCensusMember.ZRH_Rut__c,
                GroupCensusMember.ZRH_TipoCuentaBancaria__c,
                GroupCensusMember.ZRH_TipoMovimiento__c,
                GroupCensusMember.ZRH_ValorMonedaConversion__c,
                GroupCensusMember.ZRH_ValorRentaAsegurado__c,
                GroupCensusMember.ZRH_VigenciaHistorica__c,
                GroupCensusMember.ZRH_FechaExclusion__c,
                GroupCensusMember.ZRH_InclusionRealizada__c,
                GroupCensusMember.ZRH_ExclusionRealizada__c,
                GroupCensusMember.ZRH_Poliza__c,
                GroupCensusMember.ZRH_TipoMovimiento__c
            };
    }

    public Database.QueryLocator selectGroupMembersByCensusIds(Set<Id> groupCensusIds) {      
        return Database.getQueryLocator(
            newQueryFactory(false, false, true)
            .selectField(GroupCensusMember.Id)
            .selectField(GroupCensusMember.PrimaryGroupCensusMemberId)
            .selectField(GroupCensusMember.GroupClassId)
            .selectField(GroupCensusMember.RelationshipToPrimaryMember)
            .selectField(GroupCensusMember.FirstName)
            .selectField(GroupCensusMember.LastName)
            .selectField(GroupCensusMember.Name)
            .selectField(GroupCensusMember.Email)
            .selectField(GroupCensusMember.Birthdate)
            .selectField(GroupCensusMember.Gender)
            .selectField(GroupCensusMember.PhoneNumber)
            .selectField(GroupCensusMember.Street)
            .selectField(GroupCensusMember.State)
            .selectField(GroupCensusMember.City)
            .selectField(GroupCensusMember.Country)
            .selectField(GroupCensusMember.PostalCode)
            .selectField(GroupCensusMember.PolicyStartDate)
            .selectField(GroupCensusMember.AnnualEligibleSalary)
            .selectField(GroupCensusMember.ZRH_Banco__c)
            .selectField(GroupCensusMember.ZRH_Capital__c)
            .selectField(GroupCensusMember.ZRH_CapitalVidaVoluntario__c)
            .selectField(GroupCensusMember.ZRH_CodigoMonedaRenta__c)
            .selectField(GroupCensusMember.ZRH_ClaveSincronizacion__c)
            .selectField(GroupCensusMember.ZRH_Estado__c)
            .selectField(GroupCensusMember.ZRH_FechaConversionCapital__c)
            .selectField(GroupCensusMember.ZRH_NivelEscolaridad__c)
            .selectField(GroupCensusMember.ZRH_NumeroCuentaBancaria__c)
            .selectField(GroupCensusMember.ZRH_NumeroRentas__c)
            .selectField(GroupCensusMember.ZRH_NumeroTelefonoAlternativo__c)
            .selectField(GroupCensusMember.ZRH_OmitirRequisitosAsegurabilidad__c)
            .selectField(GroupCensusMember.ZRH_Rut__c)
            .selectField(GroupCensusMember.ZRH_TipoCuentaBancaria__c)
            .selectField(GroupCensusMember.ZRH_TipoMovimiento__c)
            .selectField(GroupCensusMember.ZRH_ValorMonedaConversion__c)
            .selectField(GroupCensusMember.ZRH_ValorRentaAsegurado__c)
            .selectField(GroupCensusMember.ZRH_VigenciaHistorica__c)
            .setCondition('GroupCensusMember.GroupCensusId IN :groupCensusIds AND PrimaryGroupCensusMemberId = null')
            .toSOQL()
        );
    }

    public List<GroupCensusMember> selectGroupMembersByCensusIdsToInclude(Set<Id> groupCensusIds) {      
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(GroupCensusMember.Id);
        query.selectField(GroupCensusMember.PrimaryGroupCensusMemberId);
        query.selectField(GroupCensusMember.GroupClassId);
        query.selectField(GroupCensusMember.RelationshipToPrimaryMember);
        query.selectField(GroupCensusMember.FirstName);
        query.selectField(GroupCensusMember.LastName);
        query.selectField(GroupCensusMember.Name);
        query.selectField(GroupCensusMember.Email);
        query.selectField(GroupCensusMember.Birthdate);
        query.selectField(GroupCensusMember.Gender);
        query.selectField(GroupCensusMember.PhoneNumber);
        query.selectField(GroupCensusMember.Street);
        query.selectField(GroupCensusMember.State);
        query.selectField(GroupCensusMember.City);
        query.selectField(GroupCensusMember.Country);
        query.selectField(GroupCensusMember.PostalCode);
        query.selectField(GroupCensusMember.PolicyStartDate);
        query.selectField(GroupCensusMember.AnnualEligibleSalary);
        query.selectField(GroupCensusMember.ZRH_Banco__c);
        query.selectField(GroupCensusMember.ZRH_Capital__c);
        query.selectField(GroupCensusMember.ZRH_CapitalVidaVoluntario__c);
        query.selectField(GroupCensusMember.ZRH_CodigoMonedaRenta__c);
        query.selectField(GroupCensusMember.ZRH_ClaveSincronizacion__c);
        query.selectField(GroupCensusMember.ZRH_Estado__c);
        query.selectField(GroupCensusMember.ZRH_FechaConversionCapital__c);
        query.selectField(GroupCensusMember.ZRH_NivelEscolaridad__c);
        query.selectField(GroupCensusMember.ZRH_NumeroCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_NumeroRentas__c);
        query.selectField(GroupCensusMember.ZRH_NumeroTelefonoAlternativo__c);
        query.selectField(GroupCensusMember.ZRH_OmitirRequisitosAsegurabilidad__c);
        query.selectField(GroupCensusMember.ZRH_Rut__c);
        query.selectField(GroupCensusMember.ZRH_TipoCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_TipoMovimiento__c);
        query.selectField(GroupCensusMember.ZRH_ValorMonedaConversion__c);
        query.selectField(GroupCensusMember.ZRH_ValorRentaAsegurado__c);
        query.selectField(GroupCensusMember.ZRH_VigenciaHistorica__c);
        query.selectField(GroupCensusMember.ZRH_FechaExclusion__c);
        query.selectField(GroupCensusMember.ZRH_InclusionRealizada__c);
        query.selectField(GroupCensusMember.ZRH_Poliza__c);
        query.selectField('PrimaryGroupCensusMember.ZRH_Rut__c');
        query.selectField('PrimaryGroupCensusMember.ZRH_Poliza__c');
        query.setCondition(
            'GroupCensusMember.GroupCensusId IN :groupCensusIds ' +
            'AND ZRH_TipoMovimiento__c = \'Inclusión\' ' +
            'AND ZRH_InclusionRealizada__c = false ' +
            'AND (PrimaryGroupCensusMemberId = null OR PrimaryGroupCensusMember.ZRH_InclusionRealizada__c = true)'
        );
        return (List<GroupCensusMember>) Database.query( query.toSOQL() );
    }

    public List<GroupCensusMember> selectGroupMembersByCensusIdsToExclude(Set<Id> groupCensusIds) {      
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(GroupCensusMember.Id);
        query.selectField(GroupCensusMember.PrimaryGroupCensusMemberId);
        query.selectField(GroupCensusMember.GroupClassId);
        query.selectField(GroupCensusMember.RelationshipToPrimaryMember);
        query.selectField(GroupCensusMember.FirstName);
        query.selectField(GroupCensusMember.LastName);
        query.selectField(GroupCensusMember.Name);
        query.selectField(GroupCensusMember.Email);
        query.selectField(GroupCensusMember.Birthdate);
        query.selectField(GroupCensusMember.Gender);
        query.selectField(GroupCensusMember.PhoneNumber);
        query.selectField(GroupCensusMember.Street);
        query.selectField(GroupCensusMember.State);
        query.selectField(GroupCensusMember.City);
        query.selectField(GroupCensusMember.Country);
        query.selectField(GroupCensusMember.PostalCode);
        query.selectField(GroupCensusMember.PolicyStartDate);
        query.selectField(GroupCensusMember.AnnualEligibleSalary);
        query.selectField(GroupCensusMember.ZRH_Banco__c);
        query.selectField(GroupCensusMember.ZRH_Capital__c);
        query.selectField(GroupCensusMember.ZRH_CapitalVidaVoluntario__c);
        query.selectField(GroupCensusMember.ZRH_CodigoMonedaRenta__c);
        query.selectField(GroupCensusMember.ZRH_ClaveSincronizacion__c);
        query.selectField(GroupCensusMember.ZRH_Estado__c);
        query.selectField(GroupCensusMember.ZRH_FechaConversionCapital__c);
        query.selectField(GroupCensusMember.ZRH_NivelEscolaridad__c);
        query.selectField(GroupCensusMember.ZRH_NumeroCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_NumeroRentas__c);
        query.selectField(GroupCensusMember.ZRH_NumeroTelefonoAlternativo__c);
        query.selectField(GroupCensusMember.ZRH_OmitirRequisitosAsegurabilidad__c);
        query.selectField(GroupCensusMember.ZRH_Rut__c);
        query.selectField(GroupCensusMember.ZRH_TipoCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_TipoMovimiento__c);
        query.selectField(GroupCensusMember.ZRH_ValorMonedaConversion__c);
        query.selectField(GroupCensusMember.ZRH_ValorRentaAsegurado__c);
        query.selectField(GroupCensusMember.ZRH_VigenciaHistorica__c);
        query.selectField(GroupCensusMember.ZRH_FechaExclusion__c);
        query.selectField(GroupCensusMember.ZRH_ExclusionRealizada__c);
        query.selectField(GroupCensusMember.ZRH_Poliza__c);
        query.selectField(GroupCensusMember.ZRH_TipoMovimiento__c);
        query.selectField('PrimaryGroupCensusMember.ZRH_Rut__c');
        query.selectField('PrimaryGroupCensusMember.ZRH_Poliza__c');
        query.selectField('PrimaryGroupCensusMember.ZRH_TipoMovimiento__c');
        query.setCondition('GroupCensusMember.GroupCensusId IN :groupCensusIds ' + 
                           'AND ZRH_TipoMovimiento__c = \'Exclusión\'' + 
                           'AND (PrimaryGroupCensusMemberId = null OR PrimaryGroupCensusMember.ZRH_TipoMovimiento__c <> \'Exclusión\')' + 
                           'AND ZRH_ExclusionRealizada__c = false');
        return (List<GroupCensusMember>) Database.query( query.toSOQL() );
    }

    public List<GroupCensusMember> selectGroupMembersByCensusIdsToModify(Set<Id> groupCensusIds) {      
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(GroupCensusMember.Id);
        query.selectField(GroupCensusMember.PrimaryGroupCensusMemberId);
        query.selectField(GroupCensusMember.GroupClassId);
        query.selectField(GroupCensusMember.RelationshipToPrimaryMember);
        query.selectField(GroupCensusMember.FirstName);
        query.selectField(GroupCensusMember.LastName);
        query.selectField(GroupCensusMember.Name);
        query.selectField(GroupCensusMember.Email);
        query.selectField(GroupCensusMember.Birthdate);
        query.selectField(GroupCensusMember.Gender);
        query.selectField(GroupCensusMember.PhoneNumber);
        query.selectField(GroupCensusMember.Street);
        query.selectField(GroupCensusMember.State);
        query.selectField(GroupCensusMember.City);
        query.selectField(GroupCensusMember.Country);
        query.selectField(GroupCensusMember.PostalCode);
        query.selectField(GroupCensusMember.PolicyStartDate);
        query.selectField(GroupCensusMember.AnnualEligibleSalary);
        query.selectField(GroupCensusMember.ZRH_Banco__c);
        query.selectField(GroupCensusMember.ZRH_Capital__c);
        query.selectField(GroupCensusMember.ZRH_CapitalVidaVoluntario__c);
        query.selectField(GroupCensusMember.ZRH_CodigoMonedaRenta__c);
        query.selectField(GroupCensusMember.ZRH_ClaveSincronizacion__c);
        query.selectField(GroupCensusMember.ZRH_Estado__c);
        query.selectField(GroupCensusMember.ZRH_FechaConversionCapital__c);
        query.selectField(GroupCensusMember.ZRH_NivelEscolaridad__c);
        query.selectField(GroupCensusMember.ZRH_NumeroCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_NumeroRentas__c);
        query.selectField(GroupCensusMember.ZRH_NumeroTelefonoAlternativo__c);
        query.selectField(GroupCensusMember.ZRH_OmitirRequisitosAsegurabilidad__c);
        query.selectField(GroupCensusMember.ZRH_Rut__c);
        query.selectField(GroupCensusMember.ZRH_TipoCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_TipoMovimiento__c);
        query.selectField(GroupCensusMember.ZRH_ValorMonedaConversion__c);
        query.selectField(GroupCensusMember.ZRH_ValorRentaAsegurado__c);
        query.selectField(GroupCensusMember.ZRH_VigenciaHistorica__c);
        query.selectField(GroupCensusMember.ZRH_FechaExclusion__c);
        query.selectField(GroupCensusMember.ZRH_Poliza__c);
        query.selectField('PrimaryGroupCensusMember.ZRH_Rut__c');
        query.selectField('PrimaryGroupCensusMember.ZRH_Poliza__c');
        query.setCondition('GroupCensusMember.GroupCensusId IN :groupCensusIds AND ZRH_TipoMovimiento__c = \'Modificación\'');
        return (List<GroupCensusMember>) Database.query( query.toSOQL() );
    }

    public List<GroupCensusMember> selectDependantsFromPrimaryIds(Set<Id> primaryMemberIds) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(GroupCensusMember.Id);               
        query.selectField(GroupCensusMember.PrimaryGroupCensusMemberId);   
        query.selectField(GroupCensusMember.GroupClassId);  
        query.selectField(GroupCensusMember.RelationshipToPrimaryMember);  
        query.selectField(GroupCensusMember.FirstName);
        query.selectField(GroupCensusMember.LastName);
        query.selectField(GroupCensusMember.Name);
        query.selectField(GroupCensusMember.Email);
        query.selectField(GroupCensusMember.Birthdate);
        query.selectField(GroupCensusMember.Gender);
        query.selectField(GroupCensusMember.PhoneNumber);
        query.selectField(GroupCensusMember.Street);
        query.selectField(GroupCensusMember.State);
        query.selectField(GroupCensusMember.City);
        query.selectField(GroupCensusMember.Country);
        query.selectField(GroupCensusMember.PostalCode);
        query.selectField(GroupCensusMember.PolicyStartDate);
        query.selectField(GroupCensusMember.AnnualEligibleSalary);
        query.selectField(GroupCensusMember.ZRH_Banco__c);
        query.selectField(GroupCensusMember.ZRH_Capital__c);
        query.selectField(GroupCensusMember.ZRH_CapitalVidaVoluntario__c);
        query.selectField(GroupCensusMember.ZRH_CodigoMonedaRenta__c);
        query.selectField(GroupCensusMember.ZRH_ClaveSincronizacion__c);
        query.selectField(GroupCensusMember.ZRH_Estado__c);
        query.selectField(GroupCensusMember.ZRH_FechaConversionCapital__c);
        query.selectField(GroupCensusMember.ZRH_NivelEscolaridad__c);
        query.selectField(GroupCensusMember.ZRH_NumeroCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_NumeroRentas__c);
        query.selectField(GroupCensusMember.ZRH_NumeroTelefonoAlternativo__c);
        query.selectField(GroupCensusMember.ZRH_OmitirRequisitosAsegurabilidad__c);
        query.selectField(GroupCensusMember.ZRH_Rut__c);
        query.selectField(GroupCensusMember.ZRH_TipoCuentaBancaria__c);
        query.selectField(GroupCensusMember.ZRH_TipoMovimiento__c);
        query.selectField(GroupCensusMember.ZRH_ValorMonedaConversion__c);
        query.selectField(GroupCensusMember.ZRH_ValorRentaAsegurado__c);
        query.selectField(GroupCensusMember.ZRH_VigenciaHistorica__c);
        query.selectField('PrimaryGroupCensusMember.GroupClassId');
        query.setCondition('PrimaryGroupCensusMemberId IN :primaryMemberIds');
        return (List<GroupCensusMember>) Database.query( query.toSOQL() );
    }

    public List<GroupCensusMember> selectPrimaryMembersFromRutsAndCensusIds(Set<String> primaryMemberRuts, Set<Id> censusIds) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.selectField(GroupCensusMember.Id);               
        query.selectField(GroupCensusMember.GroupCensusId);               
        query.setCondition('ZRH_Rut__c IN :primaryMemberRuts AND GroupCensusId IN :censusIds');
        return (List<GroupCensusMember>) Database.query( query.toSOQL() );
    }

}