force-app/main/default/objects/ZRH_RutaIntegracion__mdt/ZRH_RutaIntegracion__mdt.object-meta.xml
<CustomObject>
    <label>ZRH Ruta Integracion</label>
    <pluralLabel>ZRH Rutas Integraciones</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZRH_RutaIntegracion__mdt/fields/ZRH_Cabeceras__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Cabeceras__c</fullName>
    <label>Cabeceras</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ZRH_RutaIntegracion__mdt/fields/ZRH_Metodo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Metodo__c</fullName>
    <label>Método</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_RutaIntegracion__mdt/fields/ZRH_RutaURL__c.field-meta.xml
<CustomField>
    <fullName>ZRH_RutaURL__c</fullName>
    <label>Ruta URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_RutaIntegracion__mdt/fields/ZRH_ServicioIntegracion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ServicioIntegracion__c</fullName>
    <label>Servicio Integracion</label>
    <referenceTo>ZRH_ServicioIntegracion__mdt</referenceTo>
    <relationshipLabel>Rutas Integraciones</relationshipLabel>
    <relationshipName>RutasIntegraciones</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/ZRH_RutaIntegracionesSelector.cls
/*********************************************************************************
Project      : 
Created By   : Deloitte
Created Date : 19/10/2023
Description  : Query factory for Ruta Integracion using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                      ACRONYM
Abdon Tejos O.              ATO
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO			19/10/2023		initial version
********************************************************************************/
public inherited sharing class ZRH_RutaIntegracionesSelector  extends fflib_SObjectSelector{

    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       Abdon Tejos Deloitte, atejoso@deloitte.com
    *  @Date:        19/10/2023
    */
    public Schema.SObjectType getSObjectType(){
        return ZRH_RutaIntegracion__mdt.sObjectType;
    }

    /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        19/10/2023
    */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            ZRH_RutaIntegracion__mdt.Id,
            ZRH_RutaIntegracion__mdt.DeveloperName,
            ZRH_RutaIntegracion__mdt.MasterLabel,
            ZRH_RutaIntegracion__mdt.Language,
            ZRH_RutaIntegracion__mdt.NamespacePrefix,
            ZRH_RutaIntegracion__mdt.Label,
            ZRH_RutaIntegracion__mdt.QualifiedApiName,
            ZRH_RutaIntegracion__mdt.SystemModstamp,
            ZRH_RutaIntegracion__mdt.ZRH_Cabeceras__c,
            ZRH_RutaIntegracion__mdt.ZRH_Metodo__c,
            ZRH_RutaIntegracion__mdt.ZRH_RutaURL__c,
            ZRH_RutaIntegracion__mdt.ZRH_ServicioIntegracion__c
        };
    }

    /**
    *  @Description: Perform a query with the default fields with the DeveloperName of Ruta Integracion as a condition
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        19/10/2023
    */
    public List<ZRH_RutaIntegracion__mdt> selectAll(){
        fflib_QueryFactory query = newQueryFactory();
        return (List<ZRH_RutaIntegracion__mdt>) Database.query( query.toSOQL() );
    }
}