force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/ZRH_ConfiguracionTraduccion__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type que almacena las traducciones funcionales de los JSON tags de los campos ZRH_Tarifa__c, ZRH_AtributosRequisitosAsegurabilidad__c,  ZRH_AtributosReqMedicosSeleccionado__c.
,</description>
    <label>Configuración de Traducción</label>
    <pluralLabel>Configuración de Traducción</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_Campo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Campo__c</fullName>
    <label>Campo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_Estructura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Estructura__c</fullName>
    <label>Estructura</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_Objeto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Objeto__c</fullName>
    <label>Objeto</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_Orden__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Orden__c</fullName>
    <label>Orden</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_Plan__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Plan__c</fullName>
    <label>Plan</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_SubEstructura__c.field-meta.xml
<CustomField>
    <fullName>ZRH_SubEstructura__c</fullName>
    <label>Sub Estructura</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_Tag__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Tag__c</fullName>
    <label>Tag</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_ConfiguracionTraduccion__mdt/fields/ZRH_TraduccionFuncional__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TraduccionFuncional__c</fullName>
    <label>Traducción Funcional</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZRH_ConfiguracionTraduccionesSelector.cls
/*********************************************************************************
Project      : 
Created By   : Deloitte
Created Date : 26/09/2023
Description  : Query factory for StaticResorces using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                      ACRONYM
Abdon Tejos O.              ATO
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO			26/09/2023		initial version
********************************************************************************/
public inherited sharing class ZRH_ConfiguracionTraduccionesSelector extends fflib_SObjectSelector {

    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public Schema.SObjectType getSObjectType() {
        return ZRH_ConfiguracionTraduccion__mdt.sObjectType;
    }

    /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            ZRH_ConfiguracionTraduccion__mdt.Id,
            ZRH_ConfiguracionTraduccion__mdt.DeveloperName,
            ZRH_ConfiguracionTraduccion__mdt.MasterLabel,
            ZRH_ConfiguracionTraduccion__mdt.Language,
            ZRH_ConfiguracionTraduccion__mdt.NamespacePrefix,
            ZRH_ConfiguracionTraduccion__mdt.Label,
            ZRH_ConfiguracionTraduccion__mdt.QualifiedApiName,
            ZRH_ConfiguracionTraduccion__mdt.SystemModstamp,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_Tag__c,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_TraduccionFuncional__c,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_Estructura__c,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_SubEstructura__c,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_Objeto__c,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_Campo__c,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_Plan__c,
            ZRH_ConfiguracionTraduccion__mdt.ZRH_Orden__c
        };
    }

    /**
    *  @Description: Perform a query with the default fields with the Name of Glosas as a condition
    *  @Autor:       Abdon Tejos, Deloitte, atejoso@deloitte.com
    *  @Date:        27/09/2023
    */
    public List<ZRH_ConfiguracionTraduccion__mdt> selectAll() {
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        return (List<ZRH_ConfiguracionTraduccion__mdt>) Database.query( query.toSOQL() );
    }
}