force-app/main/default/objects/ZRH_SincronizacionEndoso__c/ZRH_SincronizacionEndoso__c.object-meta.xml
<CustomObject>
    <label>Sincronización de Endoso</label>
    <nameField>
        <displayFormat>SE-{00000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sincronización de Endosos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_CampoCondicion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CampoCondicion__c</fullName>
    <description>Cuando en el campo JSON se guarden una lista se debe agregar el campo que hace único en cada item.</description>
    <label>Campo Condición</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_CampoCondicionDos__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CampoCondicionDos__c</fullName>
    <label>Campo Condición Dos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_CampoCondicionTres__c.field-meta.xml
<CustomField>
    <fullName>ZRH_CampoCondicionTres__c</fullName>
    <label>Campo Condición Tres</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_Estado__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ingresado</fullName>
                <default>true</default>
                <label>Ingresado</label>
            </value>
            <value>
                <fullName>Procesado</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_Folio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Folio__c</fullName>
    <label>Folio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_GrupoNegocio__c.field-meta.xml
<CustomField>
    <fullName>ZRH_GrupoNegocio__c</fullName>
    <description>Código Grupo de Negocio para Cuenta Holding</description>
    <label>Código Grupo de Negocio</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_NombreAtributo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreAtributo__c</fullName>
    <description>Guarda el nombre del atributo que se quiere actualizar</description>
    <label>Nombre de Atributo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_NombreCampo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreCampo__c</fullName>
    <description>Guarda el nombre del campo que se va a actualizar.</description>
    <label>Nombre del Campo Salesforce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_NombreObjeto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_NombreObjeto__c</fullName>
    <description>Almacenará el nombre del objeto que se desea actualizar.</description>
    <label>Nombre del Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_ObservacionError__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ObservacionError__c</fullName>
    <label>Observación Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_TipoCampo__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoCampo__c</fullName>
    <description>Guarda s</description>
    <label>Tipo de Campo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campo Salesforce</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_TipoEndoso__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoEndoso__c</fullName>
    <description>Definición del tipo de endoso que se esta realizando</description>
    <label>Tipo de Endoso</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ZRH_TipoEndoso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_TipoObjeto__c.field-meta.xml
<CustomField>
    <fullName>ZRH_TipoObjeto__c</fullName>
    <description>Guarda el tipo de objeto que se quiere actualizar.</description>
    <label>Tipo de Objeto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Cobertura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_Valor__c.field-meta.xml
<CustomField>
    <fullName>ZRH_Valor__c</fullName>
    <description>Valor del campo o atributo que se quiere actualizar</description>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_ValorCondicion__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ValorCondicion__c</fullName>
    <description>Guarda el valor del campo que es condición para actualizar el registro.</description>
    <label>Valor Condición</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_ValorCondicionDos__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ValorCondicionDos__c</fullName>
    <label>Valor Condición Dos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZRH_SincronizacionEndoso__c/fields/ZRH_ValorCondicionTres__c.field-meta.xml
<CustomField>
    <fullName>ZRH_ValorCondicionTres__c</fullName>
    <label>Valor Condición Tres</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ZRH_TipoEndoso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>E-056</fullName>
        <label>Datos de Cobranza</label>
    </customValue>
    <customValue>
        <fullName>E-033</fullName>
        <label>Datos Cláusulas Especiales</label>
    </customValue>
    <customValue>
        <fullName>E-035</fullName>
        <label>Datos Corredores Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-009</fullName>
        <label>Modif. Datos Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-015</fullName>
        <label>Datos Cond.Coberturas Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-023</fullName>
        <label>Modif. Capital/Renta (Vida)</label>
    </customValue>
    <customValue>
        <fullName>E-042</fullName>
        <label>Datos Asegurabilidad Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-043</fullName>
        <label>Datos Contribución Empresa Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-055</fullName>
        <label>Datos Liquid. Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-101</fullName>
        <label>Datos Grales. Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-102</fullName>
        <label>Datos Tarifa Salud (Tipo/Número Integrantes) Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-103</fullName>
        <label>Datos Tarifa Salud (N° de Integrantes por/Por Tipo de Integrantes por Edad) Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-104</fullName>
        <label>Datos Deduc. por Tramo Pólizas</label>
    </customValue>
    <customValue>
        <fullName>E-105</fullName>
        <label>Datos Tarifa Escolaridad Pólizas</label>
    </customValue>
    <description>Definición del tipo de endoso que se esta realizando</description>
    <masterLabel>Tipo de Endoso</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ZRH_SincronizacionEndososSelector.cls
/*********************************************************************************
Project      : Zurich Salesforce - Seguros Colectivos
Created By   : Deloitte
Created Date : 8/1/2024
Description  : Query factory for SincronizacionEndoso using "FFLIB – Selector layer"
History      : 
--------------------------ACRONYM OF AUTHORS-------------------------------------
AUTHOR                            ACRONYM
Luis Enrique Castañeda.             LEC
---------------------------------------------------------------------------------
VERSION  AUTHOR         DATE            Description
1.0      ATO		  8/1/2024		  initial version
********************************************************************************/
public class ZRH_SincronizacionEndososSelector extends fflib_SObjectSelector {

    /**
    *  @Description: Defines the type of object handled in the selector
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        8/1/2024
    */
    public Schema.SObjectType getSObjectType(){
        return ZRH_SincronizacionEndoso__c.sObjectType;
    }
    
    
     /**
    *  @Description: Defines the fields that will be queried in a default query
    *  @Autor:       LEC, Deloitte, lcastanedad@deloitte.com
    *  @Date:        8/1/2024
    */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            ZRH_SincronizacionEndoso__c.Id,
            ZRH_SincronizacionEndoso__c.ZRH_CampoCondicion__c,
            ZRH_SincronizacionEndoso__c.ZRH_CampoCondicionDos__c,
            ZRH_SincronizacionEndoso__c.ZRH_CampoCondicionTres__c,
            ZRH_SincronizacionEndoso__c.ZRH_GrupoNegocio__c,
            ZRH_SincronizacionEndoso__c.ZRH_Estado__c,
            ZRH_SincronizacionEndoso__c.ZRH_Folio__c,
            ZRH_SincronizacionEndoso__c.ZRH_NombreAtributo__c,
            ZRH_SincronizacionEndoso__c.ZRH_NombreCampo__c,
            ZRH_SincronizacionEndoso__c.ZRH_NombreObjeto__c,
            ZRH_SincronizacionEndoso__c.ZRH_ObservacionError__c,
            ZRH_SincronizacionEndoso__c.ZRH_TipoCampo__c,
            ZRH_SincronizacionEndoso__c.ZRH_TipoEndoso__c,
            ZRH_SincronizacionEndoso__c.ZRH_TipoObjeto__c,
            ZRH_SincronizacionEndoso__c.ZRH_Valor__c,
            ZRH_SincronizacionEndoso__c.ZRH_ValorCondicion__c,
            ZRH_SincronizacionEndoso__c.ZRH_ValorCondicionDos__c,
            ZRH_SincronizacionEndoso__c.ZRH_ValorCondicionTres__c
        };
    }
    
    
    /**
    *  @Description: Perform a query by the Condition as a parameter.
    *  @Autor:       Luis Castañeda, Deloitte, lcastanedad@deloitte.com
    *  @Date:        17/11/2023
    */
    public Database.QueryLocator selectByDynamicCondition(String queryCondition) { 
        fflib_QueryFactory query = newQueryFactory(false, false, true);
        query.setCondition(queryCondition);
        return Database.getQueryLocator(query.toSOQL());
    }
}